//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ac
    {
        public int AcNo { get; set; }
        public string Nm { get; set; }
        public string AcCode { get; set; }
        public string AcGr { get; set; }
        public byte Res { get; set; }
        public byte TxCl { get; set; }
        public int TxCd { get; set; }
        public byte InpTxCd { get; set; }
        public byte Trn { get; set; }
        public byte Susp { get; set; }
        public int Cur { get; set; }
        public byte InpQty { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public byte InpR1 { get; set; }
        public byte InpR2 { get; set; }
        public byte InpR3 { get; set; }
        public byte InpR4 { get; set; }
        public byte InpR5 { get; set; }
        public byte InpR6 { get; set; }
        public int DstGr { get; set; }
        public byte ExpAut { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int RepGr { get; set; }
        public string RepCd { get; set; }
        public string ProdNo { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public byte Per { get; set; }
        public int OldAcNo { get; set; }
        public byte TxCtrl { get; set; }
        public int NwAcNo { get; set; }
        public string WebPg { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public byte InpR7 { get; set; }
        public byte InpR8 { get; set; }
        public byte InpR9 { get; set; }
        public byte InpR10 { get; set; }
        public byte InpR11 { get; set; }
        public byte InpR12 { get; set; }
        public string MemoFNm { get; set; }
        public string Nm2 { get; set; }
        public string Nm3 { get; set; }
        public decimal ExRt { get; set; }
        public int Cur2 { get; set; }
        public decimal ExRt2 { get; set; }
        public int BalProc { get; set; }
        public int AcProc { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
