//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActPrc
    {
        public int Prc { get; set; }
        public int Func { get; set; }
        public string TabFl { get; set; }
        public int SesNo { get; set; }
        public string SesId { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public long CmdNo { get; set; }
        public long ProcNo { get; set; }
        public long RepNo { get; set; }
        public byte[] TabFlB { get; set; }
    }
}
