//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcTr
    {
        public int JNo { get; set; }
        public int EntNo { get; set; }
        public int AcNo { get; set; }
        public int VoNo { get; set; }
        public int VoDt { get; set; }
        public int ValDt { get; set; }
        public short AcYr { get; set; }
        public short AcPr { get; set; }
        public int VoTp { get; set; }
        public string Txt { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CurAm { get; set; }
        public decimal AcAm { get; set; }
        public decimal Qty { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public short TxYr { get; set; }
        public short TxTrm { get; set; }
        public decimal EntAm { get; set; }
        public decimal Bas { get; set; }
        public decimal VatAm { get; set; }
        public decimal InvTxAm { get; set; }
        public int TxCd { get; set; }
        public decimal VatRt { get; set; }
        public decimal InvTxRt { get; set; }
        public int Task { get; set; }
        public int Cust { get; set; }
        public int Emp { get; set; }
        public string Act { get; set; }
        public byte SrcTp { get; set; }
        public int SrcJNo { get; set; }
        public int Err { get; set; }
        public byte AgAcCl { get; set; }
        public int AgAcNo { get; set; }
        public int Ctrl { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string InvoNo { get; set; }
        public byte Cr { get; set; }
        public decimal WthRt { get; set; }
        public decimal WthAm { get; set; }
        public decimal CstP { get; set; }
        public decimal CstAm { get; set; }
        public int Sup { get; set; }
        public int PropNo { get; set; }
        public byte ExAut { get; set; }
        public string Txt2 { get; set; }
        public int VoGr1 { get; set; }
        public int VoGr2 { get; set; }
        public int PrevVoNo { get; set; }
        public int TransSt { get; set; }
        public byte TxCl { get; set; }
        public int TmpTr { get; set; }
        public short TxYrVoD { get; set; }
        public short TxTrmVoD { get; set; }
        public int TxStNo { get; set; }
        public string PictNo { get; set; }
        public string WebPg { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int Un { get; set; }
        public int PrBt { get; set; }
        public int UpdBndNo { get; set; }
        public int UpdLnNo { get; set; }
        public int AcYrPr { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public decimal CurCExRt { get; set; }
        public decimal CurCAm { get; set; }
        public int CurCDt { get; set; }
        public int CurCRNo { get; set; }
        public decimal LastCAm { get; set; }
        public string ExtRef1 { get; set; }
        public string ExtRef2 { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public string ExtRef3 { get; set; }
        public int Cur2 { get; set; }
        public decimal ExRt2 { get; set; }
        public decimal CurAm2 { get; set; }
        public decimal CalcVAm { get; set; }
        public decimal VATDiff { get; set; }
        public int RealJNo { get; set; }
        public int RealLnNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int Ctry { get; set; }
        public short EsTxTrm { get; set; }
        public int EsTxStNo { get; set; }
    }
}
