//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AdNo { get; set; }
        public string Nm { get; set; }
        public string Ad1 { get; set; }
        public string Ad2 { get; set; }
        public string Ad3 { get; set; }
        public string Ad4 { get; set; }
        public string PNo { get; set; }
        public string PArea { get; set; }
        public int Ctry { get; set; }
        public int Lang { get; set; }
        public string Shrt { get; set; }
        public string MailAd { get; set; }
        public string Phone { get; set; }
        public string PrivPh { get; set; }
        public string MobPh { get; set; }
        public string Pers { get; set; }
        public string Fax { get; set; }
        public string Title { get; set; }
        public int LiaAd { get; set; }
        public int Trade { get; set; }
        public int Distr { get; set; }
        public string BsNo { get; set; }
        public int NoOfEmp { get; set; }
        public decimal Turn { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public int SrcNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public int AdPro { get; set; }
        public int ActNo { get; set; }
        public string NoteNm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
