//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agr
    {
        public int AgrActNo { get; set; }
        public int AgrNo { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public short FrTm { get; set; }
        public short ToTm { get; set; }
        public decimal NoReg { get; set; }
        public decimal NoInvoAb { get; set; }
        public int Pri { get; set; }
        public int DyPri { get; set; }
        public string ProdNo { get; set; }
        public int ActNo { get; set; }
        public int LiaActNo { get; set; }
        public int OrdNo { get; set; }
        public string Descr { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int RspTp { get; set; }
        public byte Priv { get; set; }
        public short RsvTm { get; set; }
        public byte RsvTmUn { get; set; }
        public byte Ntf { get; set; }
        public int NtfTm { get; set; }
        public byte NtfTmUn { get; set; }
        public byte Fin { get; set; }
        public int FinDt { get; set; }
        public byte StrSt { get; set; }
        public int Invo { get; set; }
        public string NoteNm { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CrActNo { get; set; }
        public int Dt1 { get; set; }
        public short Tm1 { get; set; }
        public int Dt2 { get; set; }
        public short Tm2 { get; set; }
        public int PropNo { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Descr2 { get; set; }
        public string ExtID { get; set; }
        public byte ExtProc { get; set; }
        public decimal ChExt { get; set; }
        public int CustNo { get; set; }
        public int InvoCust { get; set; }
        public string Txt1 { get; set; }
        public string Txt2 { get; set; }
        public int TransGr { get; set; }
        public int MaAgrAct { get; set; }
        public int MaAgrNo { get; set; }
        public int ResNo { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int RefNo { get; set; }
        public int AcYrPr { get; set; }
        public decimal CCstPr { get; set; }
        public decimal CIncCst { get; set; }
        public decimal DPr { get; set; }
        public decimal DAm { get; set; }
        public int D1Hr { get; set; }
        public int D2Hr { get; set; }
        public int D3Hr { get; set; }
        public int D4Hr { get; set; }
        public int D5Hr { get; set; }
        public int D6Hr { get; set; }
        public int D7Hr { get; set; }
        public int OrdLnNo { get; set; }
        public decimal Price { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public int AgrProc { get; set; }
        public decimal CstPr { get; set; }
        public decimal IncCst { get; set; }
        public string WageSrt { get; set; }
        public int ProdPrGr { get; set; }
        public int ProdPrG2 { get; set; }
        public int ProdPrG3 { get; set; }
        public int CustPrGr { get; set; }
        public int CustPrG2 { get; set; }
        public int CustPrG3 { get; set; }
        public int StcNo { get; set; }
        public int EmpNo { get; set; }
        public int Un { get; set; }
        public int PrM1 { get; set; }
        public int PrM2 { get; set; }
        public int PrM3 { get; set; }
        public int PrM4 { get; set; }
        public int PrM5 { get; set; }
        public decimal Dc1P { get; set; }
        public int Dupl { get; set; }
        public int Dup2 { get; set; }
        public decimal Am { get; set; }
        public int WageRtNo { get; set; }
        public int EmpPrGr { get; set; }
        public decimal Dc1Am { get; set; }
        public decimal Dc1DAm { get; set; }
        public int AdWage1 { get; set; }
        public int AdWage2 { get; set; }
        public short GMT { get; set; }
        public int AgrTmZn { get; set; }
        public int ActTmZn { get; set; }
        public string CreUsr { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public int TSGrNo { get; set; }
        public int TSBFrYrPr { get; set; }
        public int TSBToYrPr { get; set; }
        public int TSProc { get; set; }
        public int CAcSet { get; set; }
        public int WgRunNo { get; set; }
        public int DebDy { get; set; }
        public decimal NoRegDy { get; set; }
        public decimal NoInvoDy { get; set; }
        public int Rsp { get; set; }
        public int ChTmms { get; set; }
        public int ProdProcNo { get; set; }
    }
}
