//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltinnLog
    {
        public int SeqNo { get; set; }
        public int Dt { get; set; }
        public short Tm { get; set; }
        public string BatchID { get; set; }
        public int SendRef { get; set; }
        public int SchNo { get; set; }
        public int SchSpec { get; set; }
        public int St { get; set; }
        public string RecRef { get; set; }
        public int PrCd { get; set; }
        public short Pr { get; set; }
        public short Yr { get; set; }
        public string FileNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string CID { get; set; }
        public string MsgTp { get; set; }
        public string Msg { get; set; }
        public string SubmRef { get; set; }
        public string WrkFlRef { get; set; }
        public string ArchRef { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
