//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aut
    {
        public int LnNo { get; set; }
        public int AcNo { get; set; }
        public byte DbAcCl { get; set; }
        public int DbAcNo { get; set; }
        public int DbTxCd { get; set; }
        public byte CrAcCl { get; set; }
        public int CrAcNo { get; set; }
        public int CrTxCd { get; set; }
        public decimal Shr { get; set; }
        public decimal Am { get; set; }
        public int Exc { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int Blank { get; set; }
        public byte TxCdProc { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int SelR1 { get; set; }
        public int SelR2 { get; set; }
        public int SelR3 { get; set; }
        public int SelR4 { get; set; }
        public int SelR5 { get; set; }
        public int SelR6 { get; set; }
        public string SelR7 { get; set; }
        public string SelR8 { get; set; }
        public string SelR9 { get; set; }
        public string SelR10 { get; set; }
        public string SelR11 { get; set; }
        public string SelR12 { get; set; }
        public int DstK { get; set; }
        public int PrK { get; set; }
        public byte ExpAut { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
