//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAc
    {
        public int ActNo { get; set; }
        public int LnNo { get; set; }
        public string BankG { get; set; }
        public int GiroChSm { get; set; }
        public int BankCon { get; set; }
        public int ExPro { get; set; }
        public string Descr { get; set; }
        public int PmtMt { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int AcNo { get; set; }
        public int AgAcNo { get; set; }
        public int PmtCur { get; set; }
        public string CrCdKey { get; set; }
        public string ExpPr { get; set; }
        public int IntGr { get; set; }
        public int ClIntTp { get; set; }
        public int SuitNo { get; set; }
        public int AgCustNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
