//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCon
    {
        public int BCNo { get; set; }
        public string Nm { get; set; }
        public string SwftCd { get; set; }
        public string SwftAd1 { get; set; }
        public string SwftAd2 { get; set; }
        public string SwftAd3 { get; set; }
        public string SwftAd4 { get; set; }
        public string BGiro { get; set; }
        public byte CurAc { get; set; }
        public int CurNo { get; set; }
        public int GenAcNo { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public int LiaActNo { get; set; }
        public string Branch { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public string IBAN { get; set; }
    }
}
