//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgtLn
    {
        public int BgNo { get; set; }
        public int LnNo { get; set; }
        public int Dt { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public int OrdNo { get; set; }
        public string ProdNo { get; set; }
        public int EmpNo { get; set; }
        public int CustNo { get; set; }
        public int SupNo { get; set; }
        public int AcNo { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string Txt { get; set; }
        public int Un { get; set; }
        public decimal StUnRt { get; set; }
        public decimal FrNo { get; set; }
        public decimal ToNo { get; set; }
        public decimal DbIncNo { get; set; }
        public int WageRtNo { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CstPr { get; set; }
        public decimal DbCurAm { get; set; }
        public decimal DbIncCst { get; set; }
        public decimal CrInvoNo { get; set; }
        public decimal SalePr { get; set; }
        public decimal Dc1P { get; set; }
        public decimal Dc1Am { get; set; }
        public decimal Dc2P { get; set; }
        public decimal Dc2Am { get; set; }
        public decimal CrCurAm { get; set; }
        public decimal CrInvoAm { get; set; }
        public int Gr { get; set; }
        public int EntSt { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int PropNo { get; set; }
        public string MemoNo { get; set; }
        public string AcGr { get; set; }
        public byte Wk { get; set; }
        public int DstK { get; set; }
        public int PrK { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int AcYrPr { get; set; }
        public int Cur2 { get; set; }
        public decimal ExRt2 { get; set; }
        public decimal DbCurAm2 { get; set; }
        public decimal CrCurAm2 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
