//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPart
    {
        public int BPartNo { get; set; }
        public string FrFileNm { get; set; }
        public string ToFileNm { get; set; }
        public string CustNo { get; set; }
        public string Div { get; set; }
        public string Oper { get; set; }
        public int LstTrfDt { get; set; }
        public int LstDySq { get; set; }
        public int LstSq { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string ImFileNm { get; set; }
        public string ExFileNm { get; set; }
        public string Passw { get; set; }
        public string NwPassw { get; set; }
        public byte BankSys { get; set; }
        public string BankG { get; set; }
        public int BankCon { get; set; }
        public int RmtAc { get; set; }
        public int RmtFeeAc { get; set; }
        public int CNtDy { get; set; }
        public int EFTProc { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public int CurCd { get; set; }
        public int AbCst { get; set; }
        public int DeclCd { get; set; }
        public int PmtLnPro { get; set; }
        public string BankNm { get; set; }
        public int Cur { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public string EftSep { get; set; }
        public string NtfCd { get; set; }
        public string NtfTxt { get; set; }
        public string TxtCd { get; set; }
        public string TxtLn { get; set; }
        public int VoSrNo { get; set; }
        public string DeclTxt { get; set; }
        public int EftFrmTp { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public string ApSigKey { get; set; }
    }
}
