//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPmtLn
    {
        public int BPmtNo { get; set; }
        public int LnNo { get; set; }
        public int CurNo { get; set; }
        public decimal ExchRt { get; set; }
        public decimal CAm { get; set; }
        public decimal DAm { get; set; }
        public byte LnSt { get; set; }
        public int SupNo { get; set; }
        public int JNo { get; set; }
        public int EntNo { get; set; }
        public string RetCd { get; set; }
        public int SugDt { get; set; }
        public int RecDt { get; set; }
        public int ValDt { get; set; }
        public int BatDt { get; set; }
        public string BankRef { get; set; }
        public decimal RlExchRt { get; set; }
        public int DySq { get; set; }
        public string PmtAc { get; set; }
        public string RecRef { get; set; }
        public int DeclCd { get; set; }
        public string DeclTxt { get; set; }
        public int PmtDt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string TxtCd { get; set; }
        public string TxtLn { get; set; }
        public int PmtLnPro { get; set; }
        public decimal ActAm { get; set; }
        public string AbCst { get; set; }
        public string DmCst { get; set; }
        public decimal AgExchRt { get; set; }
        public string AgWt { get; set; }
        public int TrmCtr { get; set; }
        public decimal TrmRt { get; set; }
        public string ChkCd { get; set; }
        public string TlxFax { get; set; }
        public string TlxCtrCd { get; set; }
        public string TlxFaxNo { get; set; }
        public string Att { get; set; }
        public string Cid { get; set; }
        public string NtfCd { get; set; }
        public string NtfTxt { get; set; }
        public string BankG { get; set; }
        public int BankSeq { get; set; }
        public decimal Prv { get; set; }
        public int EmpNo { get; set; }
        public int GiroChSm { get; set; }
        public int CustNo { get; set; }
        public int BankAcLn { get; set; }
        public int CNtDy { get; set; }
        public int CurCd { get; set; }
        public int PmtCur { get; set; }
        public decimal TrfExRt { get; set; }
        public int BPartNo { get; set; }
        public int EftFrmTp { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
