//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPmt
    {
        public int BPmtNo { get; set; }
        public int BPartNo { get; set; }
        public string CreUsr { get; set; }
        public int TrfDt { get; set; }
        public string Descr { get; set; }
        public int PlTrfDt { get; set; }
        public string ToFileNm { get; set; }
        public byte PmtSt { get; set; }
        public int FrDySq { get; set; }
        public int ToDySq { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int PmtTp { get; set; }
        public int CurCd { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string ApReqId { get; set; }
    }
}
