//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombMat
    {
        public int CombG { get; set; }
        public int LnNo { get; set; }
        public byte AcCl { get; set; }
        public int FrAcNo { get; set; }
        public int ToAcNo { get; set; }
        public int FrR1 { get; set; }
        public int ToR1 { get; set; }
        public int FrR2 { get; set; }
        public int ToR2 { get; set; }
        public int FrR3 { get; set; }
        public int ToR3 { get; set; }
        public int FrR4 { get; set; }
        public int ToR4 { get; set; }
        public int FrR5 { get; set; }
        public int ToR5 { get; set; }
        public int FrR6 { get; set; }
        public int ToR6 { get; set; }
        public string FrR7 { get; set; }
        public string ToR7 { get; set; }
        public string FrR8 { get; set; }
        public string ToR8 { get; set; }
        public string FrR9 { get; set; }
        public string ToR9 { get; set; }
        public string FrR10 { get; set; }
        public string ToR10 { get; set; }
        public string FrR11 { get; set; }
        public string ToR11 { get; set; }
        public string FrR12 { get; set; }
        public string ToR12 { get; set; }
        public int FrEmpNo { get; set; }
        public int ToEmpNo { get; set; }
        public string FrProdNo { get; set; }
        public string ToProdNo { get; set; }
        public int Comb { get; set; }
        public int CombPro { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int FrResNo { get; set; }
        public int ToResNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
