//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsDoc
    {
        public int CsDocNo { get; set; }
        public int DocTp { get; set; }
        public int DocNo { get; set; }
        public int LtrNo { get; set; }
        public string CID { get; set; }
        public int DocDt { get; set; }
        public int StDt { get; set; }
        public int DueDt { get; set; }
        public decimal CurAm { get; set; }
        public decimal Am { get; set; }
        public int FormNo { get; set; }
        public int LayNo { get; set; }
        public int PgElNo { get; set; }
        public int CsDPro { get; set; }
        public int ActNo { get; set; }
        public string Nm { get; set; }
        public string Ad1 { get; set; }
        public string Ad2 { get; set; }
        public string Ad3 { get; set; }
        public string Ad4 { get; set; }
        public string PNo { get; set; }
        public string PArea { get; set; }
        public int Ctry { get; set; }
        public int Lang { get; set; }
        public string Shrt { get; set; }
        public string MailAd { get; set; }
        public string Phone { get; set; }
        public string PrivPh { get; set; }
        public string MobPh { get; set; }
        public string Pers { get; set; }
        public string Fax { get; set; }
        public int CustNo { get; set; }
        public string Title { get; set; }
        public int LiaAct { get; set; }
        public int Seller { get; set; }
        public int Buyer { get; set; }
        public int Rsp { get; set; }
        public int Att { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public decimal CrLmt { get; set; }
        public byte CrSusp { get; set; }
        public string CrEval { get; set; }
        public byte ExVat { get; set; }
        public int Cur { get; set; }
        public int InvoCust { get; set; }
        public string FactNo { get; set; }
        public int CPmtTrm { get; set; }
        public int CPmtMt { get; set; }
        public string BGiro { get; set; }
        public string PGiro { get; set; }
        public int DebFrDt { get; set; }
        public int DebToDt { get; set; }
        public byte MaxRems { get; set; }
        public int LstRemDt { get; set; }
        public byte LstRemNo { get; set; }
        public decimal IntRt { get; set; }
        public int RmtPri { get; set; }
        public int RmtSup { get; set; }
        public string OurCNo { get; set; }
        public int Trade { get; set; }
        public int Distr { get; set; }
        public string BsNo { get; set; }
        public decimal Turn { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public string NoteNm { get; set; }
        public string Branch { get; set; }
        public byte DirDeb { get; set; }
        public decimal MaxDebAm { get; set; }
        public int CustPref { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public string YrRef { get; set; }
        public string Fax2 { get; set; }
        public string EUTaxNo { get; set; }
        public int DocSMt { get; set; }
        public int MainAct { get; set; }
        public short MaxDueP { get; set; }
        public short MaxDueDy { get; set; }
        public int AcDocSMt { get; set; }
        public int ActPro { get; set; }
        public string IntAd1 { get; set; }
        public string IntAd2 { get; set; }
        public string EANLocCd { get; set; }
        public int OlAcNo { get; set; }
        public int ClReAcNo { get; set; }
        public int ClBaAcNo { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int GiroChSm { get; set; }
        public int BankCon { get; set; }
        public string ViPNo { get; set; }
        public string ViPArea { get; set; }
        public int RemPrDt { get; set; }
        public int IntGr { get; set; }
        public int CNtDy { get; set; }
        public int FCNo { get; set; }
        public int Cl3AcNo { get; set; }
        public decimal AgrChBal { get; set; }
        public decimal CurFee { get; set; }
        public decimal Fee { get; set; }
        public int Cur2 { get; set; }
        public int CustPre2 { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
