//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctry
    {
        public int CtryNo { get; set; }
        public string ISO { get; set; }
        public string Nm { get; set; }
        public int Lang { get; set; }
        public int Cur { get; set; }
        public decimal InvoAm { get; set; }
        public decimal InvoFee { get; set; }
        public int FeeVat { get; set; }
        public short GrcDy { get; set; }
        public byte AftRem { get; set; }
        public short Intv { get; set; }
        public byte IntMt { get; set; }
        public byte CmpInt { get; set; }
        public decimal FrmRt { get; set; }
        public decimal PrvRt { get; set; }
        public decimal MinTrAm { get; set; }
        public decimal MinNtAm { get; set; }
        public decimal IntFee { get; set; }
        public int PmtTrm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string NatCd { get; set; }
        public string NatCd2 { get; set; }
        public int RemPmt { get; set; }
        public short IntFrDy { get; set; }
        public short MxIntDy { get; set; }
        public int CtryPro { get; set; }
        public int StTxCd { get; set; }
        public byte StTxCl { get; set; }
        public short GrcDyCsh { get; set; }
        public int LgtIBAN { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
