//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cur
    {
        public int CurNo { get; set; }
        public string ISO { get; set; }
        public string Nm { get; set; }
        public byte CurTp { get; set; }
        public decimal SalesRt { get; set; }
        public decimal CalcRt { get; set; }
        public decimal PurcRt { get; set; }
        public decimal TrLmt1 { get; set; }
        public decimal TrAm1 { get; set; }
        public decimal TrLmt2 { get; set; }
        public decimal TrAm2 { get; set; }
        public decimal TrLmt3 { get; set; }
        public decimal TrAm3 { get; set; }
        public decimal IntTrAm { get; set; }
        public string BankG { get; set; }
        public int IntAc { get; set; }
        public int FeeAc { get; set; }
        public int RmtAc { get; set; }
        public int ObFeeAc { get; set; }
        public int FrFeeAc { get; set; }
        public int ExFeeAc { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int EUFeeAc { get; set; }
        public int BankCon { get; set; }
        public int RmtFeeAc { get; set; }
        public int IIFeeAc { get; set; }
        public decimal Factor { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
