//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurCData
    {
        public int JNo { get; set; }
        public int EntNo { get; set; }
        public int AcNo { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CurAm { get; set; }
        public decimal AcAm { get; set; }
        public decimal CorExRt { get; set; }
        public decimal CorAm { get; set; }
        public int CorDt { get; set; }
        public decimal NewCRt { get; set; }
        public decimal NewCAm { get; set; }
        public decimal CorDP { get; set; }
        public decimal CorDAm { get; set; }
        public decimal ACorDP { get; set; }
        public decimal ACorDAm { get; set; }
        public byte AcCl { get; set; }
        public int TransSt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal LastCAm { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
