//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustBal
    {
        public int CustNo { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public decimal DbIB { get; set; }
        public decimal DbCh { get; set; }
        public decimal DbCurIB { get; set; }
        public decimal DbCurCh { get; set; }
        public decimal DbQtyIB { get; set; }
        public decimal DbQtyCh { get; set; }
        public decimal DbTrnIB { get; set; }
        public decimal DbTrnCh { get; set; }
        public decimal OrdIB { get; set; }
        public decimal OrdCh { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal CrIB { get; set; }
        public decimal CrCh { get; set; }
        public decimal CrCurIB { get; set; }
        public decimal CrCurCh { get; set; }
        public decimal CrQtyIB { get; set; }
        public decimal CrQtyCh { get; set; }
        public decimal CrTrnIB { get; set; }
        public decimal CrTrnCh { get; set; }
        public decimal OlIB { get; set; }
        public decimal OlCh { get; set; }
        public decimal ClReIB { get; set; }
        public decimal ClReCh { get; set; }
        public decimal ClBaIB { get; set; }
        public decimal ClBaCh { get; set; }
        public decimal Cl3IB { get; set; }
        public decimal Cl3Ch { get; set; }
        public decimal DbCur2IB { get; set; }
        public decimal DbCur2Ch { get; set; }
        public decimal CrCur2IB { get; set; }
        public decimal CrCur2Ch { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
