//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecFVar
    {
        public string NmSp { get; set; }
        public string VarNm { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
        public decimal Val3 { get; set; }
        public decimal Val4 { get; set; }
        public decimal Val5 { get; set; }
        public decimal Val6 { get; set; }
        public decimal Val7 { get; set; }
        public decimal Val8 { get; set; }
        public decimal Val9 { get; set; }
        public decimal Val10 { get; set; }
        public decimal Val11 { get; set; }
        public decimal Val12 { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
