//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelAlt
    {
        public string ProdNo { get; set; }
        public int LnNo { get; set; }
        public int SupNo { get; set; }
        public string SupProd { get; set; }
        public string SupDescr { get; set; }
        public int SrcCtry { get; set; }
        public int StPurcUn { get; set; }
        public decimal EcPurcQt { get; set; }
        public byte PurcPrc { get; set; }
        public short DelTm { get; set; }
        public decimal FrAm { get; set; }
        public decimal CusAm { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal FrAm2 { get; set; }
        public decimal FrAm3 { get; set; }
        public decimal FrAm4 { get; set; }
        public short TanspTm { get; set; }
        public int Buyer { get; set; }
        public int Rsp1 { get; set; }
        public int Rsp2 { get; set; }
        public short AdmTm { get; set; }
        public int FrCusPro { get; set; }
        public decimal SupStock { get; set; }
        public decimal SupPrice { get; set; }
        public string IntAd { get; set; }
        public decimal Reg1 { get; set; }
        public decimal Reg2 { get; set; }
        public decimal Reg3 { get; set; }
        public decimal Reg4 { get; set; }
        public decimal Reg5 { get; set; }
        public decimal Reg6 { get; set; }
        public decimal Reg7 { get; set; }
        public decimal Reg8 { get; set; }
        public short ProdTm { get; set; }
        public decimal StUnRt { get; set; }
        public string NoteNm { get; set; }
        public decimal DCstAdP { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
