//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelTmBal
    {
        public string ProdNo { get; set; }
        public int StcNo { get; set; }
        public int DelDt { get; set; }
        public decimal InO { get; set; }
        public decimal CInO { get; set; }
        public decimal InHireO { get; set; }
        public decimal CInHireO { get; set; }
        public decimal InLoanO { get; set; }
        public decimal CInLoanO { get; set; }
        public decimal ExpLoss { get; set; }
        public decimal CExpLoss { get; set; }
        public decimal InProdO { get; set; }
        public decimal CInProdO { get; set; }
        public decimal InPurc { get; set; }
        public decimal CInPurc { get; set; }
        public decimal InProd { get; set; }
        public decimal CInProd { get; set; }
        public decimal InTrfO { get; set; }
        public decimal CInTrfO { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int YrWk { get; set; }
        public decimal Conf { get; set; }
        public decimal Sent { get; set; }
        public decimal DecOuts { get; set; }
        public decimal RsvOuts { get; set; }
        public decimal IncBal { get; set; }
        public decimal ClosBal { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
