//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DfLn
    {
        public int DfNo { get; set; }
        public int LnNo { get; set; }
        public string Txt { get; set; }
        public string AcGr { get; set; }
        public byte Sgn { get; set; }
        public byte PTrn { get; set; }
        public int AcLn { get; set; }
        public string FFm { get; set; }
        public int FSz { get; set; }
        public int FSt { get; set; }
        public int LnFl { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string NmSp { get; set; }
        public string FreeTxt1 { get; set; }
        public int IndLvl { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int DfLnPrc { get; set; }
    }
}
