//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public int DocNo { get; set; }
        public int VerNo { get; set; }
        public string FileNm { get; set; }
        public int ProgNo { get; set; }
        public string Descr { get; set; }
        public int FileCrDt { get; set; }
        public int FileChDt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte Inc { get; set; }
        public int DocGr { get; set; }
        public int CrActNo { get; set; }
        public int MainDoc { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public string Psw { get; set; }
        public string Inf { get; set; }
        public int TemplLnNo { get; set; }
        public int TemplTpNo { get; set; }
        public int RunNo { get; set; }
        public int Icon { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
