//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DstKey
    {
        public int DstGr { get; set; }
        public string Descr { get; set; }
        public decimal SmR1 { get; set; }
        public decimal SmR2 { get; set; }
        public decimal SmR3 { get; set; }
        public decimal SmR4 { get; set; }
        public decimal SmR5 { get; set; }
        public decimal SmR6 { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal SmR7 { get; set; }
        public decimal SmR8 { get; set; }
        public decimal SmR9 { get; set; }
        public decimal SmR10 { get; set; }
        public decimal SmR11 { get; set; }
        public decimal SmR12 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
