//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDITrLog
    {
        public int SeqNo { get; set; }
        public int Dt { get; set; }
        public short Tm { get; set; }
        public string Usr { get; set; }
        public int DocTp { get; set; }
        public int DocSize { get; set; }
        public int TransSt { get; set; }
        public string DocNo { get; set; }
        public int NoOfSh { get; set; }
        public string OutMed { get; set; }
        public string TransID { get; set; }
        public string Party { get; set; }
        public decimal Am { get; set; }
        public string MsgID { get; set; }
        public int RetCd { get; set; }
        public string FileNm { get; set; }
        public string StAsTxt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int FormId { get; set; }
        public byte MsgTp { get; set; }
        public int MsgLnNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
