//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtConf
    {
        public int PK { get; set; }
        public int MsgTp { get; set; }
        public string ObNm { get; set; }
        public string ObTxt { get; set; }
        public int ObNo { get; set; }
        public int PrgNo { get; set; }
        public int CfFl { get; set; }
        public int ExFrNo { get; set; }
        public int ExToNo { get; set; }
        public int InFrNo { get; set; }
        public int InToNo { get; set; }
        public string TbNm1 { get; set; }
        public string TbNm2 { get; set; }
        public string ColNm1 { get; set; }
        public string Sep1 { get; set; }
        public string ColNm2 { get; set; }
        public string Sep2 { get; set; }
        public string Exp1 { get; set; }
        public string Exp2 { get; set; }
        public string Exp3 { get; set; }
        public string Exp4 { get; set; }
        public string Txt1 { get; set; }
        public string Txt2 { get; set; }
        public string Txt3 { get; set; }
        public string Txt4 { get; set; }
        public int Gr1 { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string Descr { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
