//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactComp
    {
        public int FCNo { get; set; }
        public string ImpFNm { get; set; }
        public string FactFNm { get; set; }
        public int LstRnDt { get; set; }
        public int LstRnNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int FactPro { get; set; }
        public int FactCust { get; set; }
        public string FactID { get; set; }
        public byte CIDFact { get; set; }
        public string FactCID { get; set; }
        public int CIDProc { get; set; }
        public byte CIDCust { get; set; }
        public byte CIDRef { get; set; }
        public string Nm { get; set; }
        public string BGiro { get; set; }
        public int OCRAcB { get; set; }
        public int VoSr { get; set; }
        public byte CIDFrm { get; set; }
        public int RmtFeeAc { get; set; }
        public string CustNo { get; set; }
        public int AgAcNo { get; set; }
        public short BefDueDy { get; set; }
        public string RecpFile { get; set; }
        public string RecpImp { get; set; }
        public string ChgFile { get; set; }
        public string ChgImp { get; set; }
        public string PaymFile { get; set; }
        public string PaymImp { get; set; }
        public string CredDep1 { get; set; }
        public string CredDep2 { get; set; }
        public string SqlFltSP { get; set; }
        public string FrTxtReF { get; set; }
        public string BrkTxt1 { get; set; }
        public string BrkTxt2 { get; set; }
        public int DyBefDed { get; set; }
        public int DirDebSt { get; set; }
        public int LnInvSrc { get; set; }
        public int EftErrAc { get; set; }
        public int AgioVTp2 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
