//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeInf1
    {
        public int PK { get; set; }
        public int ActNo { get; set; }
        public int Cust { get; set; }
        public int Sup { get; set; }
        public int Emp { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int OrdNo { get; set; }
        public int OrdLnNo { get; set; }
        public string ProdNo { get; set; }
        public int StrLnNo { get; set; }
        public int DelLnNo { get; set; }
        public int StcNo { get; set; }
        public int OrdJNo { get; set; }
        public int ProdTrNo { get; set; }
        public int AcNo { get; set; }
        public byte AcCl { get; set; }
        public int VoJNo { get; set; }
        public int EntNo { get; set; }
        public int BgNo { get; set; }
        public int BgLnNo { get; set; }
        public int AgrRefNo { get; set; }
        public short AcYr { get; set; }
        public short AcPr { get; set; }
        public short TxYr { get; set; }
        public short TxTrm { get; set; }
        public int StYrPr { get; set; }
        public int BndNo { get; set; }
        public int BndLnNo { get; set; }
        public int FrInfTp { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public string Txt1 { get; set; }
        public string Txt2 { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public int Dt3 { get; set; }
        public int Dt4 { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
        public decimal Val3 { get; set; }
        public decimal Val4 { get; set; }
        public decimal Val5 { get; set; }
        public decimal Val6 { get; set; }
        public decimal Val7 { get; set; }
        public decimal Val8 { get; set; }
        public decimal Val9 { get; set; }
        public decimal Val10 { get; set; }
        public decimal Val11 { get; set; }
        public decimal Val12 { get; set; }
        public decimal Val13 { get; set; }
        public decimal Val14 { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string Txt3 { get; set; }
        public string Txt4 { get; set; }
        public int MainFrI1 { get; set; }
        public int FreeInf2 { get; set; }
        public int FreeInf3 { get; set; }
        public string PictFNm { get; set; }
        public string WebPg { get; set; }
        public string NoteNm { get; set; }
        public int InfCatNo { get; set; }
        public int PrCatNo { get; set; }
        public int Dt5 { get; set; }
        public int Dt6 { get; set; }
        public int Dt7 { get; set; }
        public int Dt8 { get; set; }
        public int Dt9 { get; set; }
        public int Dt10 { get; set; }
        public int Dt11 { get; set; }
        public int Dt12 { get; set; }
        public int Dt13 { get; set; }
        public int Dt14 { get; set; }
        public int PropNo { get; set; }
        public int PriceLn { get; set; }
        public int ShpNo { get; set; }
        public int FrInfTp2 { get; set; }
        public int FrInfTp3 { get; set; }
        public decimal Val15 { get; set; }
        public decimal Val16 { get; set; }
        public decimal Val17 { get; set; }
        public decimal Val18 { get; set; }
        public decimal Val19 { get; set; }
        public decimal Val20 { get; set; }
        public decimal Val21 { get; set; }
        public decimal Val22 { get; set; }
        public decimal Val23 { get; set; }
        public decimal Val24 { get; set; }
        public decimal Val25 { get; set; }
        public decimal Val26 { get; set; }
        public decimal Val27 { get; set; }
        public decimal Val28 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public int ResNo { get; set; }
        public int TsGrNo { get; set; }
        public int YrPr { get; set; }
        public int PrtSeqNo { get; set; }
        public int AdNo { get; set; }
        public int ProgNo { get; set; }
        public int TemplLnNo { get; set; }
        public int DocNo { get; set; }
        public int DocVerNo { get; set; }
        public int DocLkLnNo { get; set; }
        public int BankLnNo { get; set; }
        public int PrxNo { get; set; }
        public int RealJNo { get; set; }
        public int RealLnNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
