//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLoc
    {
        public string ProdNo { get; set; }
        public int StcNo { get; set; }
        public string Loc { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string LocInf1 { get; set; }
        public decimal MaxQtyUn { get; set; }
        public int ItmLocProc { get; set; }
        public decimal Cntable { get; set; }
        public int CntGr { get; set; }
        public int LstCntDt { get; set; }
        public string CntBy { get; set; }
        public decimal CntDf { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
