//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc
    {
        public int StcNo { get; set; }
        public string Loc1 { get; set; }
        public string PhysLoc { get; set; }
        public string Descr { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public int LocProc { get; set; }
        public string ProdNo { get; set; }
        public decimal Lgt { get; set; }
        public decimal Wdt { get; set; }
        public decimal Hgt { get; set; }
        public decimal Area { get; set; }
        public decimal Volume { get; set; }
        public decimal Wgt { get; set; }
        public decimal UsdVol { get; set; }
        public decimal UsdWgt { get; set; }
        public decimal UsdQty { get; set; }
        public decimal FreeVol { get; set; }
        public decimal FreeWgt { get; set; }
        public decimal FreeQty { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
