//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaCustTr
    {
        public int JNo { get; set; }
        public int EntNo { get; set; }
        public int AgJNo { get; set; }
        public int AgEntNo { get; set; }
        public int PayedDt { get; set; }
        public decimal CurAm { get; set; }
        public decimal Am { get; set; }
        public decimal InCurAm { get; set; }
        public decimal CurIntAm { get; set; }
        public decimal IntAm { get; set; }
        public int IntFrDt { get; set; }
        public int IntToDt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
