//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpSupTr
    {
        public int JNo { get; set; }
        public int EntNo { get; set; }
        public int SupNo { get; set; }
        public int VoNo { get; set; }
        public int VoDt { get; set; }
        public int ValDt { get; set; }
        public short AcYr { get; set; }
        public short AcPr { get; set; }
        public int VoTp { get; set; }
        public string Txt { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CurAm { get; set; }
        public decimal RCurAm { get; set; }
        public decimal Am { get; set; }
        public decimal RAm { get; set; }
        public int DueDt { get; set; }
        public int PayedDt { get; set; }
        public int OrdNo { get; set; }
        public string InvoNo { get; set; }
        public string Ref { get; set; }
        public string AgRef { get; set; }
        public decimal Purc { get; set; }
        public byte St { get; set; }
        public int Pri { get; set; }
        public string CID { get; set; }
        public int Att { get; set; }
        public int AttDt1 { get; set; }
        public int AttDt2 { get; set; }
        public byte ExcRmt { get; set; }
        public int EstPayDt { get; set; }
        public int RmtRnNo { get; set; }
        public int GenAcNo { get; set; }
        public decimal Qty { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public byte SrcTp { get; set; }
        public int SrcJNo { get; set; }
        public int Err { get; set; }
        public byte AgAcCl { get; set; }
        public int AgAcNo { get; set; }
        public int Ctrl { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte Cr { get; set; }
        public int PmtTrm { get; set; }
        public int CshDueDt { get; set; }
        public decimal CshCurAm { get; set; }
        public decimal CshAm { get; set; }
        public decimal PrtCurAm { get; set; }
        public decimal PrtAm { get; set; }
        public string Txt2 { get; set; }
        public string BankG { get; set; }
        public int VoGr1 { get; set; }
        public int VoGr2 { get; set; }
        public decimal FixCurAm { get; set; }
        public decimal FixAm { get; set; }
        public int PrevVoNo { get; set; }
        public int AttVoNo { get; set; }
        public int TransSt { get; set; }
        public int EFT1 { get; set; }
        public int EFT2 { get; set; }
        public int EFT3 { get; set; }
        public int EFT4 { get; set; }
        public decimal VatAm { get; set; }
        public int BPmtNo { get; set; }
        public int TmpTr { get; set; }
        public decimal CNAm { get; set; }
        public int DelActNo { get; set; }
        public string PictNo { get; set; }
        public string WebPg { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int GiroChSm { get; set; }
        public int PmtMt { get; set; }
        public int Un { get; set; }
        public int PrBt { get; set; }
        public int UpdBndNo { get; set; }
        public int UpdLnNo { get; set; }
        public int AcYrPr { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public int BankCon { get; set; }
        public int BankAcLn { get; set; }
        public int PmtCur { get; set; }
        public decimal TrfExRt { get; set; }
        public decimal CurCExRt { get; set; }
        public decimal CurCAm { get; set; }
        public int CurCDt { get; set; }
        public int CurCRNo { get; set; }
        public decimal LastCAm { get; set; }
        public decimal RemCAm { get; set; }
        public string ExtRef1 { get; set; }
        public string ExtRef2 { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public string ExtRef3 { get; set; }
        public int Cur2 { get; set; }
        public decimal ExRt2 { get; set; }
        public decimal CurAm2 { get; set; }
        public decimal CRCshAm { get; set; }
        public decimal RCshAm { get; set; }
        public int EftFrmTp { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int Ctry { get; set; }
    }
}
