//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdDBa
    {
        public int OrdDBNo { get; set; }
        public int DocType { get; set; }
        public string XmlFNm { get; set; }
        public int SuppNo { get; set; }
        public int CustNo { get; set; }
        public int RmitNo { get; set; }
        public int Pref { get; set; }
        public int Stat { get; set; }
        public string InvoNo { get; set; }
        public string InvoRef { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public int InvDt { get; set; }
        public int DueDt { get; set; }
        public decimal NOrdSum { get; set; }
        public decimal InvoFee { get; set; }
        public decimal TotFrAm { get; set; }
        public decimal ExclVatAm { get; set; }
        public decimal VatAm { get; set; }
        public decimal VatBasAm { get; set; }
        public decimal VatFreeAm { get; set; }
        public decimal InclVatAm { get; set; }
        public decimal RoundAm { get; set; }
        public decimal InvoAm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string Cid { get; set; }
        public string ErrMsg { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
