//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdLnBa
    {
        public int OrdDBNo { get; set; }
        public int OrdSeqNo { get; set; }
        public int OrdLnSeqNo { get; set; }
        public int OrdNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int OrdLnNo { get; set; }
        public string ProdNo { get; set; }
        public decimal DeliQty { get; set; }
        public decimal Price { get; set; }
        public decimal DcAm { get; set; }
        public decimal DcP { get; set; }
        public decimal DcBAm { get; set; }
        public decimal VatAm { get; set; }
        public decimal VatP { get; set; }
        public decimal VatBAm { get; set; }
        public decimal DVatAm { get; set; }
        public decimal DVatBAm { get; set; }
        public int CfDelDt { get; set; }
        public int DelDt { get; set; }
        public string Descr { get; set; }
        public string ErrMsg { get; set; }
        public int ExID { get; set; }
        public int Stat { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
