//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLDFDocU
    {
        public int RowNo { get; set; }
        public int DocNo { get; set; }
        public string DocTxt { get; set; }
        public string FileNm { get; set; }
        public string FileExt { get; set; }
        public string OrgFNm { get; set; }
        public int Flags { get; set; }
        public int DueDt { get; set; }
        public string CID { get; set; }
        public int NxtDueDt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
