//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLDFDatU
    {
        public int RowNo { get; set; }
        public int DocNo { get; set; }
        public string Usr { get; set; }
        public string Nm { get; set; }
        public string MailAd { get; set; }
        public int Srt { get; set; }
        public int DueDt { get; set; }
        public int ProcTp { get; set; }
        public int Flags { get; set; }
        public string Descr { get; set; }
        public string Owner { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int ProcTpId { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
