//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmtAgr
    {
        public int LnNo { get; set; }
        public int FCNo { get; set; }
        public int CustNo { get; set; }
        public int PmtCd { get; set; }
        public int RegTp { get; set; }
        public string AgrId { get; set; }
        public int PerTp { get; set; }
        public int DueTp { get; set; }
        public decimal AgrAm { get; set; }
        public decimal LstChrAm { get; set; }
        public decimal AccAm { get; set; }
        public int ValFrDt { get; set; }
        public int ValToDt { get; set; }
        public int ChrDt { get; set; }
        public int DueDt { get; set; }
        public int ComCd { get; set; }
        public string PayerInf { get; set; }
        public string Descr { get; set; }
        public string RefCID { get; set; }
        public int LstRunNo { get; set; }
        public int LstVoNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string PrevPNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
