//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmtTrm
    {
        public int PmtTrmNo { get; set; }
        public string Descr { get; set; }
        public byte CrMth { get; set; }
        public short CrDy { get; set; }
        public byte DcMth { get; set; }
        public short DcDy { get; set; }
        public decimal DcP { get; set; }
        public int IncDcAc { get; set; }
        public int OutwDcAc { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte DirDeb { get; set; }
        public byte EDIPmtT { get; set; }
        public short GrcDy { get; set; }
        public short IntFrDy { get; set; }
        public short MxIntDy { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
