//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrDcMat
    {
        public int LnNo { get; set; }
        public int OrdNo { get; set; }
        public int OrdPrGr { get; set; }
        public string ProdNo { get; set; }
        public int ProdPrGr { get; set; }
        public int StcNo { get; set; }
        public int EmpNo { get; set; }
        public int EmpPrGr { get; set; }
        public int WageRtNo { get; set; }
        public int CustNo { get; set; }
        public int CustPrGr { get; set; }
        public int SupNo { get; set; }
        public string StrProd { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public int Un { get; set; }
        public decimal MinNo { get; set; }
        public int Cur { get; set; }
        public decimal SalePr { get; set; }
        public decimal SaleDcP { get; set; }
        public decimal SaleDcAm { get; set; }
        public decimal HirePr { get; set; }
        public decimal HireDcP { get; set; }
        public decimal HireDcAm { get; set; }
        public decimal CompPr { get; set; }
        public decimal SugPr { get; set; }
        public decimal CstPr { get; set; }
        public int PurcCur { get; set; }
        public decimal PurcPr { get; set; }
        public decimal PurcDcP { get; set; }
        public decimal PurcDcAm { get; set; }
        public string Descr { get; set; }
        public string WageSrt { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CstCur { get; set; }
        public decimal MinAm { get; set; }
        public int PrCatNo { get; set; }
        public int PrCatDt { get; set; }
        public int ProdPrG2 { get; set; }
        public int ProdPrG3 { get; set; }
        public int CustPrG2 { get; set; }
        public int ShpNo { get; set; }
        public decimal NWgtL { get; set; }
        public decimal LgtL { get; set; }
        public decimal AreaL { get; set; }
        public decimal VolL { get; set; }
        public decimal NoUn { get; set; }
        public int Gross { get; set; }
        public int VatNo { get; set; }
        public int Fixed { get; set; }
        public byte InclStr { get; set; }
        public int PrTp { get; set; }
        public byte PrUn { get; set; }
        public decimal Lim { get; set; }
        public decimal SalePr2 { get; set; }
        public decimal Lim2 { get; set; }
        public decimal SalePr3 { get; set; }
        public decimal MaxAm { get; set; }
        public byte Split { get; set; }
        public decimal SPrAdd { get; set; }
        public string FrPNo { get; set; }
        public string ToPNo { get; set; }
        public int DelTrm { get; set; }
        public int DelMt { get; set; }
        public decimal Lim3 { get; set; }
        public decimal SalePr4 { get; set; }
        public decimal Lim4 { get; set; }
        public decimal SalePr5 { get; set; }
        public decimal Lim5 { get; set; }
        public decimal SalePr6 { get; set; }
        public decimal Lim6 { get; set; }
        public decimal SalePr7 { get; set; }
        public byte CpSPr { get; set; }
        public decimal SDc2P { get; set; }
        public decimal SDc2Am { get; set; }
        public decimal SDc3P { get; set; }
        public decimal SDc3Am { get; set; }
        public decimal SDc4P { get; set; }
        public decimal SDc4Am { get; set; }
        public decimal SDc5P { get; set; }
        public decimal SDc5Am { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int CustPrG3 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int GrPrTxCd { get; set; }
        public int SCPrSt { get; set; }
        public string SCd { get; set; }
        public int ChTmms { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
