//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod
    {
        public string ProdNo { get; set; }
        public string Descr { get; set; }
        public int ProdGr { get; set; }
        public int ProdTp { get; set; }
        public int StSaleUn { get; set; }
        public int ProdPrGr { get; set; }
        public int SpecFunc { get; set; }
        public int ExcPrint { get; set; }
        public int EditPref { get; set; }
        public int EdFmt { get; set; }
        public int ExpStr { get; set; }
        public int PrM2b { get; set; }
        public string WageSrt { get; set; }
        public decimal DesMrg { get; set; }
        public int NrmStc { get; set; }
        public int ProcMt { get; set; }
        public decimal NWgtU { get; set; }
        public decimal TareU { get; set; }
        public decimal VolU { get; set; }
        public string CusStNo { get; set; }
        public string RepProd { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public decimal ExQty { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal CstPrAdd { get; set; }
        public byte GrSep { get; set; }
        public long EUStatNo { get; set; }
        public int ProdTp2 { get; set; }
        public decimal FrNo { get; set; }
        public decimal ToNo { get; set; }
        public decimal Factor3 { get; set; }
        public byte InvoPlLn { get; set; }
        public int Rsp { get; set; }
        public int Buyer { get; set; }
        public int ProdPrG2 { get; set; }
        public int ProdPrG3 { get; set; }
        public decimal LgtU { get; set; }
        public decimal WdtU { get; set; }
        public decimal HgtU { get; set; }
        public decimal AreaU { get; set; }
        public byte Measure { get; set; }
        public decimal StUnRt { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public int ProdTp3 { get; set; }
        public int ProdTp4 { get; set; }
        public string TrInf1 { get; set; }
        public string TrInf2 { get; set; }
        public int Rsp2 { get; set; }
        public byte PrUn { get; set; }
        public decimal PrNo { get; set; }
        public decimal DensU { get; set; }
        public byte TrTp { get; set; }
        public decimal TrAm { get; set; }
        public int PrM1b { get; set; }
        public int PrM1c { get; set; }
        public int PrM2c { get; set; }
        public int PrM3b { get; set; }
        public int PrM3c { get; set; }
        public int PrM4b { get; set; }
        public int PrM4c { get; set; }
        public int PrM5b { get; set; }
        public int PrM5c { get; set; }
        public string PictNo { get; set; }
        public string TrInf3 { get; set; }
        public string TrInf4 { get; set; }
        public string OldPNo { get; set; }
        public decimal SPrAdd { get; set; }
        public string EANItmNo { get; set; }
        public int ProdPro { get; set; }
        public int PrCatNo { get; set; }
        public int PrCatNo2 { get; set; }
        public string NwProdNo { get; set; }
        public string WebPg2 { get; set; }
        public int PgElNo { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public int PrCatNo3 { get; set; }
        public int PrCatNo4 { get; set; }
        public int PrCatNo5 { get; set; }
        public int PrCatNo6 { get; set; }
        public int AgrProc { get; set; }
        public int NxtSerNo { get; set; }
        public int WageRtNo { get; set; }
        public int PrK { get; set; }
        public int ProdProcNo { get; set; }
        public int ChTmms { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
