//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdProc
    {
        public int ProdProcNo { get; set; }
        public int CopyProc { get; set; }
        public string Descr { get; set; }
        public int PrM1 { get; set; }
        public int PrM1b { get; set; }
        public int PrM1c { get; set; }
        public int PrM2 { get; set; }
        public int PrM2b { get; set; }
        public int PrM2c { get; set; }
        public int PrM3 { get; set; }
        public int PrM3b { get; set; }
        public int PrM3c { get; set; }
        public int PrM4 { get; set; }
        public int PrM4b { get; set; }
        public int PrM4c { get; set; }
        public int PrM5 { get; set; }
        public int PrM5b { get; set; }
        public int PrM5c { get; set; }
        public int ExpStr { get; set; }
        public int ProdPro { get; set; }
        public int AgrProc { get; set; }
        public int AdWage1 { get; set; }
        public int AdWage2 { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int ProdTp { get; set; }
        public int ProdTp2 { get; set; }
        public int ProdTp3 { get; set; }
        public int ProdTp4 { get; set; }
        public int ProdGr { get; set; }
        public string TrInf1 { get; set; }
        public string TrInf2 { get; set; }
        public string TrInf3 { get; set; }
        public string TrInf4 { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public int StcNo { get; set; }
        public int WageRtNo { get; set; }
        public string WageSrt { get; set; }
        public int ProdPrGr { get; set; }
        public int ProdPrG2 { get; set; }
        public int ProdPrG3 { get; set; }
        public int StSaleUn { get; set; }
        public decimal CstPrAdd { get; set; }
        public long EUStatNo { get; set; }
        public decimal TrAm { get; set; }
        public decimal SPrAdd { get; set; }
        public byte PrUn { get; set; }
        public string CusStNo { get; set; }
        public decimal DesMrg { get; set; }
        public int PrCatNo { get; set; }
        public int PrCatNo2 { get; set; }
        public int PrCatNo3 { get; set; }
        public int PrCatNo4 { get; set; }
        public int PrCatNo5 { get; set; }
        public int PrCatNo6 { get; set; }
        public int AcSet { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
