//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropCl
    {
        public int PropClNo { get; set; }
        public string Descr { get; set; }
        public decimal WORt { get; set; }
        public byte WOYr { get; set; }
        public int PropAc { get; set; }
        public int WOCstAc { get; set; }
        public int AccWOAc { get; set; }
        public int BalGrNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal ScrapV { get; set; }
        public int IncAcNo { get; set; }
        public int CstAcNo { get; set; }
        public int LossAcNo { get; set; }
        public int LiqAcNo { get; set; }
        public int PropPref { get; set; }
        public int WdAc { get; set; }
        public int WdWOCstAc { get; set; }
        public int WdAccWOAc { get; set; }
        public int WuAc { get; set; }
        public int WuWOCstAc { get; set; }
        public int WuAccWOAc { get; set; }
        public int AddAc { get; set; }
        public int AddWOCstAc { get; set; }
        public int AddAccWOAc { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
