//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropBal
    {
        public int PropNo { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public decimal DbIB { get; set; }
        public decimal CrIB { get; set; }
        public decimal DbCh { get; set; }
        public decimal CrCh { get; set; }
        public decimal PurcIB { get; set; }
        public decimal PurcCh { get; set; }
        public decimal AddIB { get; set; }
        public decimal AddCh { get; set; }
        public decimal WrUpIB { get; set; }
        public decimal WrUpCh { get; set; }
        public decimal WrDnIB { get; set; }
        public decimal WrDnCh { get; set; }
        public decimal WrOfIB { get; set; }
        public decimal WrOfCh { get; set; }
        public decimal SaleIB { get; set; }
        public decimal SaleCh { get; set; }
        public decimal DiscIB { get; set; }
        public decimal DiscCh { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal WAWrOfIB { get; set; }
        public decimal WAWrOfCh { get; set; }
        public decimal PuWOIB { get; set; }
        public decimal PuWOCh { get; set; }
        public decimal PuAfIB { get; set; }
        public decimal PuAfCh { get; set; }
        public decimal WOAddIB { get; set; }
        public decimal WOAddCh { get; set; }
        public decimal WOAWOIB { get; set; }
        public decimal WOAWOCh { get; set; }
        public decimal WOWUIB { get; set; }
        public decimal WOWUCh { get; set; }
        public decimal WOWUAWIB { get; set; }
        public decimal WOWUAWCh { get; set; }
        public decimal DbCurIB { get; set; }
        public decimal CrCurIB { get; set; }
        public decimal DbCurCh { get; set; }
        public decimal CrCurCh { get; set; }
        public decimal CPurcIB { get; set; }
        public decimal CPurcCh { get; set; }
        public decimal CAddIB { get; set; }
        public decimal CAddCh { get; set; }
        public decimal CWrUpIB { get; set; }
        public decimal CWrUpCh { get; set; }
        public decimal CWrDnIB { get; set; }
        public decimal CWrDnCh { get; set; }
        public decimal CWrOfIB { get; set; }
        public decimal CWrOfCh { get; set; }
        public decimal CSaleIB { get; set; }
        public decimal CSaleCh { get; set; }
        public decimal CDiscIB { get; set; }
        public decimal CDiscCh { get; set; }
        public decimal CWAWrOIB { get; set; }
        public decimal CWAWrOCh { get; set; }
        public decimal CPuWOIB { get; set; }
        public decimal CPuWOCh { get; set; }
        public decimal CWOAddIB { get; set; }
        public decimal CWOAddCh { get; set; }
        public decimal CWOWUIB { get; set; }
        public decimal CWOWUCh { get; set; }
        public decimal DbCur2IB { get; set; }
        public decimal CrCur2IB { get; set; }
        public decimal DbCur2Ch { get; set; }
        public decimal CrCur2Ch { get; set; }
        public decimal C2PurcIB { get; set; }
        public decimal C2PurcCh { get; set; }
        public decimal C2AddIB { get; set; }
        public decimal C2AddCh { get; set; }
        public decimal C2WrUpIB { get; set; }
        public decimal C2WrUpCh { get; set; }
        public decimal C2WrDnIB { get; set; }
        public decimal C2WrDnCh { get; set; }
        public decimal C2WrOfIB { get; set; }
        public decimal C2WrOfCh { get; set; }
        public decimal C2SaleIB { get; set; }
        public decimal C2SaleCh { get; set; }
        public decimal C2DiscIB { get; set; }
        public decimal C2DiscCh { get; set; }
        public decimal C2WAWrOIB { get; set; }
        public decimal C2WAWrOCh { get; set; }
        public decimal C2PuWOIB { get; set; }
        public decimal C2PuWOCh { get; set; }
        public decimal C2WOAddIB { get; set; }
        public decimal C2WOAddCh { get; set; }
        public decimal C2WOWUIB { get; set; }
        public decimal C2WOWUCh { get; set; }
        public decimal WOWdIB { get; set; }
        public decimal WOWdCh { get; set; }
        public decimal CWOWdIB { get; set; }
        public decimal CWOWdCh { get; set; }
        public decimal C2WOWdIB { get; set; }
        public decimal C2WOWdCh { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
