//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prop
    {
        public int PropNo { get; set; }
        public string Descr { get; set; }
        public int PropClNo { get; set; }
        public int PurcDt { get; set; }
        public decimal LifeTm { get; set; }
        public decimal WORt { get; set; }
        public int LstWODt { get; set; }
        public string ProdNo { get; set; }
        public string SCd { get; set; }
        public string SerNo { get; set; }
        public int SupNo { get; set; }
        public int Buyer { get; set; }
        public int Rsp { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int WarToDt { get; set; }
        public int SrvAgrNo { get; set; }
        public int SrvAgrSp { get; set; }
        public int SrvToDt { get; set; }
        public int RevalDt { get; set; }
        public decimal InsurVal { get; set; }
        public decimal EstVal { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public int TxCd { get; set; }
        public string PictFNm { get; set; }
        public string WebPg2 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public decimal ScrapV { get; set; }
        public decimal AdLifeTm { get; set; }
        public decimal WrLifeTm { get; set; }
        public decimal AdWORt { get; set; }
        public decimal WrWORt { get; set; }
        public int NewPropNo { get; set; }
        public int OldPropNo { get; set; }
        public int DstGr { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public int Cur2 { get; set; }
        public int EndDtInv { get; set; }
        public int EndDtAdd { get; set; }
        public int EndDtWrU { get; set; }
        public decimal IncAm { get; set; }
        public decimal PurcAm { get; set; }
        public decimal AccWOAm { get; set; }
        public int CustNo { get; set; }
        public int PropSt { get; set; }
        public byte TrnCl { get; set; }
        public int ProdGr { get; set; }
        public decimal ExRt2 { get; set; }
        public int PropPref { get; set; }
        public int PurcDtAdd { get; set; }
        public int PurcDtWrU { get; set; }
        public int EndDtWd { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
