//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrRep
    {
        public int SupNo { get; set; }
        public int LnNo { get; set; }
        public string ProdNo { get; set; }
        public decimal PrePrice { get; set; }
        public decimal NewPrice { get; set; }
        public decimal Bal { get; set; }
        public decimal Am { get; set; }
        public byte RepSt { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int RepNo { get; set; }
        public decimal StcInc { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal PreDPr { get; set; }
        public decimal NewDPr { get; set; }
        public decimal DAm { get; set; }
        public decimal PreDcP { get; set; }
        public decimal PreDcAm { get; set; }
        public decimal PreDcDAm { get; set; }
        public decimal NewDcP { get; set; }
        public decimal NewDcAm { get; set; }
        public decimal NewDcDAm { get; set; }
        public int Stc { get; set; }
        public int PrRepP { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
