//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurcSLn
    {
        public int PurcSNo { get; set; }
        public int LnNo { get; set; }
        public string ProdNo { get; set; }
        public int StcNo { get; set; }
        public int DelAltNo { get; set; }
        public int SupNo { get; set; }
        public int ArDt { get; set; }
        public short TanspTm { get; set; }
        public int DelDt { get; set; }
        public short DelTm { get; set; }
        public int PurcDt { get; set; }
        public int Un { get; set; }
        public decimal Num { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte Prod { get; set; }
        public decimal NumBefR { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public int OvDelDt { get; set; }
        public short ProdTm { get; set; }
        public decimal StUnRt { get; set; }
        public int ToStcNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
