//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2Bal
    {
        public int R2 { get; set; }
        public int AcNo { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public decimal DbIB { get; set; }
        public decimal DbCh { get; set; }
        public decimal DbCurIB { get; set; }
        public decimal DbCurCh { get; set; }
        public decimal DbQtyIB { get; set; }
        public decimal DbQtyCh { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal CrIB { get; set; }
        public decimal CrCh { get; set; }
        public decimal CrCurIB { get; set; }
        public decimal CrCurCh { get; set; }
        public decimal CrQtyIB { get; set; }
        public decimal CrQtyCh { get; set; }
        public decimal DbAutCh { get; set; }
        public decimal CrAutCh { get; set; }
        public decimal DbAutCCh { get; set; }
        public decimal CrAutCCh { get; set; }
        public decimal DbAutQCh { get; set; }
        public decimal CrAutQCh { get; set; }
        public decimal DbCur2IB { get; set; }
        public decimal DbCur2Ch { get; set; }
        public decimal CrCur2IB { get; set; }
        public decimal CrCur2Ch { get; set; }
        public decimal DbAutC2Ch { get; set; }
        public decimal CrAutC2Ch { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
