//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class R4
    {
        public int RNo { get; set; }
        public string Nm { get; set; }
        public string Ad1 { get; set; }
        public string Ad2 { get; set; }
        public string Ad3 { get; set; }
        public string Ad4 { get; set; }
        public string PNo { get; set; }
        public string PArea { get; set; }
        public string Prin { get; set; }
        public int Rsp { get; set; }
        public int CustNo { get; set; }
        public int SupNo { get; set; }
        public int St { get; set; }
        public int Susp { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int MainR4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public byte AccRes { get; set; }
        public int EStDt { get; set; }
        public int EEndDt { get; set; }
        public int RStDt { get; set; }
        public int REndDt { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public string IntAd { get; set; }
        public string MailAd { get; set; }
        public string PictFNm { get; set; }
        public decimal Am1 { get; set; }
        public decimal Am2 { get; set; }
        public decimal Am3 { get; set; }
        public decimal Am4 { get; set; }
        public int ActNo1 { get; set; }
        public int ActNo2 { get; set; }
        public int ActNo3 { get; set; }
        public int ActNo4 { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public int Dt3 { get; set; }
        public int Dt4 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int Ctry { get; set; }
        public int LiaActNo { get; set; }
        public int NewRNo { get; set; }
        public int OldRNo { get; set; }
        public int Cur { get; set; }
        public int Cur2 { get; set; }
        public int BalProc { get; set; }
        public int AcSet { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
