//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re
    {
        public int ResNo { get; set; }
        public string Nm { get; set; }
        public string ProdNo { get; set; }
        public int ReadInt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int TSGrNo { get; set; }
        public int EmpNo { get; set; }
        public int PropNo { get; set; }
        public int Rsp { get; set; }
        public string NoteNm { get; set; }
        public string PictFNm { get; set; }
        public string WebPg1 { get; set; }
        public string WebPg2 { get; set; }
        public int ProgNo { get; set; }
        public int TLnNo { get; set; }
        public int Un { get; set; }
        public decimal MinQty { get; set; }
        public decimal MaxQty { get; set; }
        public decimal FixedQty { get; set; }
        public int AgrProc { get; set; }
        public int DebDy { get; set; }
        public int ProdPrGr { get; set; }
        public int ProdPrG2 { get; set; }
        public int ProdPrG3 { get; set; }
        public string StdWageSrt { get; set; }
        public string OTWageSrt { get; set; }
        public int OT1WageRtN { get; set; }
        public int OT2WageRtN { get; set; }
        public int ChTmms { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
