//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealJLn
    {
        public int RealJNo { get; set; }
        public int LnNo { get; set; }
        public int OrdJNo { get; set; }
        public int TrNo { get; set; }
        public int OrdNo { get; set; }
        public int VoJNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int ValDt { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public decimal StcCh { get; set; }
        public decimal StcCst { get; set; }
        public decimal RlStcVal { get; set; }
        public int JDt { get; set; }
        public int RlOr { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
