//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rsv
    {
        public int OrdNo { get; set; }
        public int OrdLnNo { get; set; }
        public int SeqNo { get; set; }
        public int ShpNo { get; set; }
        public int TrfShpNo { get; set; }
        public string SerNo { get; set; }
        public string Loc { get; set; }
        public decimal Num { get; set; }
        public decimal NoRet { get; set; }
        public decimal NoComp { get; set; }
        public decimal NoScr { get; set; }
        public decimal NoRsv { get; set; }
        public decimal NoPic { get; set; }
        public decimal NoRlz { get; set; }
        public int RlDelDt { get; set; }
        public decimal CstPr { get; set; }
        public int DurDt { get; set; }
        public int JNo { get; set; }
        public int TrNo { get; set; }
        public int TrfJNo { get; set; }
        public int TrfTrNo { get; set; }
        public int PicRunNo { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Dupl { get; set; }
        public int CstCur { get; set; }
        public decimal CstExRt { get; set; }
        public decimal CCstPr { get; set; }
        public decimal NoFin { get; set; }
        public int RlRetDt { get; set; }
        public string FinBy { get; set; }
        public decimal Fr { get; set; }
        public decimal Fr2 { get; set; }
        public decimal Fr3 { get; set; }
        public decimal Fr4 { get; set; }
        public decimal Cus { get; set; }
        public short FinTm { get; set; }
        public decimal RetN { get; set; }
        public decimal CompN { get; set; }
        public decimal ScrN { get; set; }
        public decimal PicN { get; set; }
        public decimal RlzN { get; set; }
        public decimal FinN { get; set; }
        public string PictFNm { get; set; }
        public string TrInf1 { get; set; }
        public string TrInf2 { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public string InvoNo { get; set; }
        public int RealJNo { get; set; }
        public string ProdNo { get; set; }
        public int FrStc { get; set; }
        public byte TrTp { get; set; }
        public decimal NoRsvInc { get; set; }
        public int ToStc { get; set; }
        public decimal DCstAd { get; set; }
        public string ToLoc { get; set; }
        public decimal NoPac { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int PurcNo { get; set; }
        public int LnPurcNo { get; set; }
    }
}
