//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVo
    {
        public int RVNo { get; set; }
        public int PosID { get; set; }
        public int VoNo { get; set; }
        public int StDt { get; set; }
        public short StTm { get; set; }
        public int Seller { get; set; }
        public int CustNo { get; set; }
        public decimal DDiscAm { get; set; }
        public decimal DVatAm { get; set; }
        public decimal DAm { get; set; }
        public int EndDt { get; set; }
        public short EndTm { get; set; }
        public string CancelFl { get; set; }
        public string TstSt { get; set; }
        public int StrtSeq { get; set; }
        public int StopSeq { get; set; }
        public int CustTp { get; set; }
        public int VoTp { get; set; }
        public string St { get; set; }
        public int Dt { get; set; }
        public short Tm { get; set; }
        public int JNo { get; set; }
        public int OrdNo { get; set; }
        public int BndNo { get; set; }
        public int ElJNo { get; set; }
        public int StlmJNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
