//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVoLn
    {
        public int RVLNo { get; set; }
        public int LnNo { get; set; }
        public int VoNo { get; set; }
        public int AtSeller { get; set; }
        public decimal CurAm { get; set; }
        public string ISO { get; set; }
        public decimal TotAm { get; set; }
        public int DcTp { get; set; }
        public int DcTpEx { get; set; }
        public decimal ExRt { get; set; }
        public decimal Ds1P { get; set; }
        public decimal Dc1PAm { get; set; }
        public decimal DcTrans { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public string EANItmNo { get; set; }
        public string Descr { get; set; }
        public int UnTp { get; set; }
        public decimal VatAm { get; set; }
        public int LnTp { get; set; }
        public int VatCd { get; set; }
        public int GiftCpID { get; set; }
        public string Bank { get; set; }
        public int CheckNo { get; set; }
        public string PersonID { get; set; }
        public int PersonTp { get; set; }
        public int CrCardTp { get; set; }
        public string CrCardNm { get; set; }
        public string CrCardNo { get; set; }
        public int ExpDt { get; set; }
        public int CustNo { get; set; }
        public int VoNoRef { get; set; }
        public int PosIDRef { get; set; }
        public int ValDt { get; set; }
        public string SerNo { get; set; }
        public string R8Ref { get; set; }
        public int LnID { get; set; }
        public string RefTxt { get; set; }
        public decimal NrmUnPr { get; set; }
        public int RetReas { get; set; }
        public int ParLnID { get; set; }
        public int LnValid { get; set; }
        public string St { get; set; }
        public int Dt { get; set; }
        public short Tm { get; set; }
        public int R6 { get; set; }
        public int Un { get; set; }
        public int JNo { get; set; }
        public int OrdNo { get; set; }
        public int OrdLnNo { get; set; }
        public int BndNo { get; set; }
        public int BndLnNo { get; set; }
        public int Cur { get; set; }
        public int ElJNo { get; set; }
        public string AccID { get; set; }
        public string CostID { get; set; }
        public int EntryID { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
