//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShpBal
    {
        public string ProdNo { get; set; }
        public int StcNo { get; set; }
        public int ShpNo { get; set; }
        public string SerNo { get; set; }
        public string Loc { get; set; }
        public int SepShp { get; set; }
        public decimal RestBal { get; set; }
        public decimal NoDel { get; set; }
        public decimal NoHire { get; set; }
        public decimal NoLoan { get; set; }
        public decimal Loss { get; set; }
        public decimal NoFrProd { get; set; }
        public decimal NoRec { get; set; }
        public decimal NoProd { get; set; }
        public decimal NoTrf { get; set; }
        public decimal NoRsv { get; set; }
        public decimal StcVal { get; set; }
        public decimal CstPr { get; set; }
        public decimal FrAm { get; set; }
        public decimal CusAm { get; set; }
        public int SupNo { get; set; }
        public int OrdNo { get; set; }
        public int RecDt { get; set; }
        public int PrvDecDt { get; set; }
        public int DurDt { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal FrAm2 { get; set; }
        public decimal FrAm3 { get; set; }
        public decimal FrAm4 { get; set; }
        public int CstCur { get; set; }
        public decimal CstExRt { get; set; }
        public decimal CCstPr { get; set; }
        public decimal StcInc { get; set; }
        public decimal PhStcVal { get; set; }
        public string MemoNo { get; set; }
        public int CreDt { get; set; }
        public int ShpSt { get; set; }
        public string PictFNm { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public string TrInf1 { get; set; }
        public string TrInf2 { get; set; }
        public int OriOrdNo { get; set; }
        public int OriOLnNo { get; set; }
        public decimal Cntable { get; set; }
        public int CntGr { get; set; }
        public int LstCntDt { get; set; }
        public string CntBy { get; set; }
        public decimal CntDf { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public decimal InInc { get; set; }
        public decimal PrNo { get; set; }
        public decimal DCstAd { get; set; }
        public decimal NoRsvInc { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
