//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc
    {
        public int StcNo { get; set; }
        public string Nm { get; set; }
        public string Ad1 { get; set; }
        public string Ad2 { get; set; }
        public string Ad3 { get; set; }
        public string Ad4 { get; set; }
        public string PNo { get; set; }
        public string PArea { get; set; }
        public int Rsp { get; set; }
        public string MailAd { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string PictFNm { get; set; }
        public int Ctry { get; set; }
        public string EANLocCd { get; set; }
        public int StcPro { get; set; }
        public int MainStc { get; set; }
        public int AcSet { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
