//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StcBal
    {
        public string ProdNo { get; set; }
        public int StcNo { get; set; }
        public int NrmSup { get; set; }
        public string NrmLoc { get; set; }
        public decimal Bal { get; set; }
        public decimal InO { get; set; }
        public decimal CInO { get; set; }
        public decimal InHireO { get; set; }
        public decimal CInHireO { get; set; }
        public decimal HireBal { get; set; }
        public decimal InLoanO { get; set; }
        public decimal CInLoanO { get; set; }
        public decimal LoanBal { get; set; }
        public decimal ExpLoss { get; set; }
        public decimal CExpLoss { get; set; }
        public decimal InProdO { get; set; }
        public decimal CInProdO { get; set; }
        public decimal InPurc { get; set; }
        public decimal CInPurc { get; set; }
        public decimal InProd { get; set; }
        public decimal CInProd { get; set; }
        public decimal InTrfO { get; set; }
        public decimal CInTrfO { get; set; }
        public decimal RsvOuts { get; set; }
        public decimal ShpRsv { get; set; }
        public decimal MinBal { get; set; }
        public decimal MaxBal { get; set; }
        public int CntGr { get; set; }
        public decimal CntDf { get; set; }
        public int LstCntDt { get; set; }
        public string CntBy { get; set; }
        public decimal StcVal { get; set; }
        public decimal LPurcQty { get; set; }
        public int LPurcDt { get; set; }
        public int LSaleDt { get; set; }
        public int LShpNo { get; set; }
        public int LSrt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public decimal StcInc { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public decimal PrvCntNo { get; set; }
        public int PrvCntDt { get; set; }
        public string PrvCntBy { get; set; }
        public decimal DecrRate { get; set; }
        public decimal MinBalD { get; set; }
        public decimal MaxBalD { get; set; }
        public short AdmTm { get; set; }
        public short DelTm { get; set; }
        public short TanspTm { get; set; }
        public short PurcInt { get; set; }
        public int PurcSDt { get; set; }
        public decimal DecrPurc { get; set; }
        public int ExpArDt { get; set; }
        public decimal PurcPnt { get; set; }
        public decimal PurcPntD { get; set; }
        public decimal EcPurcQ { get; set; }
        public decimal EcPurcQD { get; set; }
        public decimal RndOff { get; set; }
        public decimal RndOffD { get; set; }
        public int PurcProc { get; set; }
        public short MntTm { get; set; }
        public short DemTm { get; set; }
        public decimal Conf { get; set; }
        public decimal Sent { get; set; }
        public int Days { get; set; }
        public byte PurcMt { get; set; }
        public byte AggrL { get; set; }
        public byte RoundMt { get; set; }
        public decimal DecIns { get; set; }
        public decimal PhCstPr { get; set; }
        public decimal PhStcVal { get; set; }
        public decimal IncIns { get; set; }
        public decimal PoPhStV { get; set; }
        public decimal PoPhStB { get; set; }
        public decimal Cntable { get; set; }
        public int StcBalSt { get; set; }
        public int PrintS { get; set; }
        public decimal NoFin { get; set; }
        public string StInf1 { get; set; }
        public string StInf2 { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public short ProdTm { get; set; }
        public decimal PicNotR { get; set; }
        public decimal AvToPic { get; set; }
        public string MemoNo { get; set; }
        public decimal LastFIFO { get; set; }
        public decimal LstFStcV { get; set; }
        public decimal ShpRsvIn { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
