//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Struct
    {
        public string ProdNo { get; set; }
        public int LnNo { get; set; }
        public string SubProd { get; set; }
        public string Descr { get; set; }
        public string ID { get; set; }
        public decimal NoPerStr { get; set; }
        public string FFm { get; set; }
        public int FSz { get; set; }
        public int FSt { get; set; }
        public int LnFl { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int PrM2 { get; set; }
        public int ProdTp1 { get; set; }
        public int ProdTp2 { get; set; }
        public int ProdTp3 { get; set; }
        public int ProdTp4 { get; set; }
        public string TrInf1 { get; set; }
        public string TrInf2 { get; set; }
        public int StrWgt { get; set; }
        public int PrM1 { get; set; }
        public int PrM3 { get; set; }
        public int PrM4 { get; set; }
        public int PrM5 { get; set; }
        public string TrInf3 { get; set; }
        public string TrInf4 { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public string Inf { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public string Inf7 { get; set; }
        public string Inf8 { get; set; }
        public int Gr { get; set; }
        public int Gr2 { get; set; }
        public int Gr3 { get; set; }
        public int Gr4 { get; set; }
        public int Gr5 { get; set; }
        public int Gr6 { get; set; }
        public int Gr7 { get; set; }
        public int Gr8 { get; set; }
        public int Gr9 { get; set; }
        public int Gr10 { get; set; }
        public int Gr11 { get; set; }
        public int Gr12 { get; set; }
        public int StcNo { get; set; }
        public string NoteNm { get; set; }
        public int ProdGr { get; set; }
        public int AcSet { get; set; }
        public int ProdProcNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
