//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskJ
    {
        public int JNo { get; set; }
        public int CustNo { get; set; }
        public int StDt { get; set; }
        public int AgEndDt { get; set; }
        public int REndDt { get; set; }
        public short Yr { get; set; }
        public short Pr { get; set; }
        public byte Term { get; set; }
        public int EmpNo { get; set; }
        public int SuitP { get; set; }
        public int LiaActNo { get; set; }
        public int Assessm { get; set; }
        public int RepFDt { get; set; }
        public int VatFDt { get; set; }
        public int TaxFDt { get; set; }
        public int SentDt { get; set; }
        public int AcSpDt { get; set; }
        public int PuncDt { get; set; }
        public int TallyDt { get; set; }
        public int InvngDt { get; set; }
        public int WgFinDt { get; set; }
        public int HolAlSDt { get; set; }
        public int WDSDt { get; set; }
        public int AcpLtDt { get; set; }
        public decimal AcrHrs { get; set; }
        public int Invd { get; set; }
        public string TskSrt { get; set; }
        public int TermAjDt { get; set; }
        public int MtAjDt { get; set; }
        public int ChEqDt { get; set; }
        public int SkAcDt { get; set; }
        public int FinAcDt { get; set; }
        public int AudActNo { get; set; }
        public int StAudDt { get; set; }
        public int AnStlDt { get; set; }
        public int AsPaDt { get; set; }
        public int PbArDt { get; set; }
        public int TxRetDt { get; set; }
        public int BoardDt { get; set; }
        public int AgrRevDt { get; set; }
        public string Inf1 { get; set; }
        public string Inf2 { get; set; }
        public string Inf3 { get; set; }
        public string Inf4 { get; set; }
        public string Inf5 { get; set; }
        public string Inf6 { get; set; }
        public string NoteNm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public int Dt3 { get; set; }
        public int Dt4 { get; set; }
        public int Dt5 { get; set; }
        public int Dt6 { get; set; }
        public int Dt7 { get; set; }
        public int Dt8 { get; set; }
        public int Dt9 { get; set; }
        public int Dt10 { get; set; }
        public int Dt11 { get; set; }
        public int Dt12 { get; set; }
        public int Dt13 { get; set; }
        public int Dt14 { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
        public decimal Val3 { get; set; }
        public decimal Val4 { get; set; }
        public decimal Val5 { get; set; }
        public decimal Val6 { get; set; }
        public decimal Val7 { get; set; }
        public decimal Val8 { get; set; }
        public decimal Val9 { get; set; }
        public decimal Val10 { get; set; }
        public decimal Val11 { get; set; }
        public decimal Val12 { get; set; }
        public decimal Val13 { get; set; }
        public decimal Val14 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
