//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAcInf
    {
        public int ProdGr { get; set; }
        public int AcSet { get; set; }
        public string Descr { get; set; }
        public int VatNo { get; set; }
        public decimal WthTxRt { get; set; }
        public byte SpcTxCd { get; set; }
        public decimal SpcTxSz { get; set; }
        public byte SpcTxVat { get; set; }
        public byte SpcTxPr { get; set; }
        public int SaleR1 { get; set; }
        public int SaleR2 { get; set; }
        public int SaleR3 { get; set; }
        public int SaleR4 { get; set; }
        public int SaleR5 { get; set; }
        public int SaleR6 { get; set; }
        public decimal TrnRt { get; set; }
        public int StcR1 { get; set; }
        public int StcR2 { get; set; }
        public int StcR3 { get; set; }
        public int StcR4 { get; set; }
        public int StcR5 { get; set; }
        public int StcR6 { get; set; }
        public int ObSaleAc { get; set; }
        public int FrSaleAc { get; set; }
        public int ExSaleAc { get; set; }
        public int ObDcAc { get; set; }
        public int FrDcAc { get; set; }
        public int ExDcAc { get; set; }
        public int ObAddAc { get; set; }
        public int FrAddAc { get; set; }
        public int ExAddAc { get; set; }
        public int ObSpcAc { get; set; }
        public int FrSpcAc { get; set; }
        public int ExSpcAc { get; set; }
        public int DbPrCst { get; set; }
        public int CrPrCst { get; set; }
        public int DbFrg { get; set; }
        public int CrFrg { get; set; }
        public int DbFrg2 { get; set; }
        public int CrFrg2 { get; set; }
        public int DbFrg3 { get; set; }
        public int CrFrg3 { get; set; }
        public int DbFrg4 { get; set; }
        public int CrFrg4 { get; set; }
        public int DbCus { get; set; }
        public int CrCus { get; set; }
        public int DbStc { get; set; }
        public int CrStc { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int EUSaleAc { get; set; }
        public int EUDcAc { get; set; }
        public int EUAddAc { get; set; }
        public int EUSpcAc { get; set; }
        public int ObPurcAc { get; set; }
        public int FrPurcAc { get; set; }
        public int EUPurcAc { get; set; }
        public int ExPurcAc { get; set; }
        public int PurcTxCd { get; set; }
        public byte OverwOrd { get; set; }
        public int TaxAcPro { get; set; }
        public string SaleR7 { get; set; }
        public string SaleR8 { get; set; }
        public string SaleR9 { get; set; }
        public string SaleR10 { get; set; }
        public string SaleR11 { get; set; }
        public string SaleR12 { get; set; }
        public string StcR7 { get; set; }
        public string StcR8 { get; set; }
        public string StcR9 { get; set; }
        public string StcR10 { get; set; }
        public string StcR11 { get; set; }
        public string StcR12 { get; set; }
        public byte TrnClSal { get; set; }
        public byte TrnClPur { get; set; }
        public int DbStcS { get; set; }
        public int CrStcS { get; set; }
        public int DbSaleS { get; set; }
        public int CrSaleS { get; set; }
        public int DbCstAd { get; set; }
        public int CrCstAd { get; set; }
        public int CstDfAc { get; set; }
        public int ReTxDc { get; set; }
        public int ReNTxDc { get; set; }
        public int ReEUDc { get; set; }
        public int ReImpDc { get; set; }
        public int AdTxDc { get; set; }
        public int AdNTxDc { get; set; }
        public int AdEUDc { get; set; }
        public int AdImpDc { get; set; }
        public int ProdWaAc { get; set; }
        public int ProdWoAc { get; set; }
        public int ProdDfAc { get; set; }
        public int ProdCfAc { get; set; }
        public int DbHrAc { get; set; }
        public int CrHrAc { get; set; }
        public int DscHrCst { get; set; }
        public int DbStcPr { get; set; }
        public int CrStcPr { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int SrvTp { get; set; }
    }
}
