//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templ
    {
        public int ProgNo { get; set; }
        public int LnNo { get; set; }
        public string FileNm { get; set; }
        public string Descr { get; set; }
        public int Srt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int TemplTp { get; set; }
        public long TabNo { get; set; }
        public int Gr { get; set; }
        public string Inf { get; set; }
        public int DocGr { get; set; }
        public string Psw { get; set; }
        public int DocProc { get; set; }
        public int AgrTxtNo { get; set; }
        public string DataPath { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
