//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSBal
    {
        public int TSGrNo { get; set; }
        public int YrPr { get; set; }
        public int ResNo { get; set; }
        public int EmpNo { get; set; }
        public short FrTm { get; set; }
        public short ToTm { get; set; }
        public short TmDy { get; set; }
        public short DeTm { get; set; }
        public int NrmTm { get; set; }
        public short NoOfWDy { get; set; }
        public int AgrBalAp { get; set; }
        public int AgrBIncTm { get; set; }
        public int AgrBInvoTm { get; set; }
        public int AgrBRsvTm { get; set; }
        public int Overtime { get; set; }
        public int FlexIB { get; set; }
        public int TrToOrdBal { get; set; }
        public int TrToWgBal { get; set; }
        public int TSBSt { get; set; }
        public int BookSt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int MaxFl { get; set; }
        public int TSProc { get; set; }
        public int FlexCor { get; set; }
        public string Inf { get; set; }
        public string NoteNm { get; set; }
        public int Gr { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
