//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCal
    {
        public int TSGrNo { get; set; }
        public int YrPr { get; set; }
        public int FrDt { get; set; }
        public int ToDt { get; set; }
        public short D1FrTm { get; set; }
        public short D1TmDy { get; set; }
        public short D2FrTm { get; set; }
        public short D2TmDy { get; set; }
        public short D3FrTm { get; set; }
        public short D3TmDy { get; set; }
        public short D4FrTm { get; set; }
        public short D4TmDy { get; set; }
        public short D5FrTm { get; set; }
        public short D5TmDy { get; set; }
        public short D6FrTm { get; set; }
        public short D6TmDy { get; set; }
        public short D7FrTm { get; set; }
        public short D7TmDy { get; set; }
        public short NoOfWDy { get; set; }
        public byte FrWkNo { get; set; }
        public byte ToWkNo { get; set; }
        public int TSGrProc { get; set; }
        public short DeTm { get; set; }
        public int NrmTm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
