//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSGr
    {
        public int TSGrNo { get; set; }
        public string Descr { get; set; }
        public short CurrYr { get; set; }
        public int CurrYrPr { get; set; }
        public int SuspYrPr { get; set; }
        public int MaxFl { get; set; }
        public int TSGrProc { get; set; }
        public int NoOfPr { get; set; }
        public short FrTm { get; set; }
        public short ToTm { get; set; }
        public short DeTm { get; set; }
        public short NrmTm { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string StdWageSrt { get; set; }
        public string OTWageSrt { get; set; }
        public int OT1WageRtN { get; set; }
        public int OT2WageRtN { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
