//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxCd
    {
        public int TxCdNo { get; set; }
        public string Descr { get; set; }
        public int VatNo { get; set; }
        public decimal WthTxRt { get; set; }
        public decimal CstP { get; set; }
        public int InvTxNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int Serv { get; set; }
        public int WgDPro { get; set; }
        public byte TrnCl { get; set; }
        public string TxInf { get; set; }
        public string Shr { get; set; }
        public int FormNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int VatRtTp { get; set; }
    }
}
