//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int Un { get; set; }
        public string Descr { get; set; }
        public decimal StUnRt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public string EDIUn { get; set; }
        public decimal NWgtU { get; set; }
        public decimal TareU { get; set; }
        public decimal LgtU { get; set; }
        public decimal WdtU { get; set; }
        public decimal HgtU { get; set; }
        public decimal AreaU { get; set; }
        public decimal VolU { get; set; }
        public byte Measure { get; set; }
        public decimal DensU { get; set; }
        public decimal PrNo { get; set; }
        public decimal Factor3 { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
