//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upd
    {
        public int JNo { get; set; }
        public int MinVoNo { get; set; }
        public int MaxVoNo { get; set; }
        public int CustTr { get; set; }
        public int SupTr { get; set; }
        public int AcTr { get; set; }
        public int TotTr { get; set; }
        public int ErrCnt { get; set; }
        public int NewBal { get; set; }
        public decimal CustCh { get; set; }
        public decimal SupCh { get; set; }
        public decimal SmDb { get; set; }
        public decimal SmCr { get; set; }
        public decimal InvTx { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int PropTr { get; set; }
        public decimal PropCh { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
