//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdMa
    {
        public int JNo { get; set; }
        public int BndNo { get; set; }
        public int LnNo { get; set; }
        public int RLnNo { get; set; }
        public string RefNo { get; set; }
        public int AgJNo { get; set; }
        public int AgEntNo { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte AgRefTp { get; set; }
        public int AgJNo2 { get; set; }
        public int AgEntNo2 { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CurAm { get; set; }
        public decimal Am { get; set; }
        public decimal PrtCurAm { get; set; }
        public decimal PrtAm { get; set; }
        public decimal PmVaCAm { get; set; }
        public decimal PmVaAm { get; set; }
        public decimal PmVaAmCD { get; set; }
        public int DbTxCdP { get; set; }
        public byte DbTrnClP { get; set; }
        public int CrTxCdP { get; set; }
        public byte CrTrnClP { get; set; }
        public byte Payed { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
