//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdVo
    {
        public int JNo { get; set; }
        public int BndNo { get; set; }
        public int LnNo { get; set; }
        public int VoNo { get; set; }
        public int VoDt { get; set; }
        public int ValDt { get; set; }
        public short AcYr { get; set; }
        public short AcPr { get; set; }
        public short TxYr { get; set; }
        public short TxTrm { get; set; }
        public int VoTp { get; set; }
        public string Txt { get; set; }
        public byte DbAcCl { get; set; }
        public int DbAcNo { get; set; }
        public int DbTxCd { get; set; }
        public byte CrAcCl { get; set; }
        public int CrAcNo { get; set; }
        public int CrTxCd { get; set; }
        public int Cur { get; set; }
        public decimal ExRt { get; set; }
        public decimal CurAm { get; set; }
        public decimal Am { get; set; }
        public decimal Qty { get; set; }
        public int DstGr { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public string InvoNo { get; set; }
        public string Ref { get; set; }
        public string AgRef { get; set; }
        public int PmtTrm { get; set; }
        public int DueDt { get; set; }
        public decimal IntRt { get; set; }
        public int Pri { get; set; }
        public byte Exc { get; set; }
        public int Att { get; set; }
        public int Task { get; set; }
        public int Cust { get; set; }
        public int Sup { get; set; }
        public int Emp { get; set; }
        public string Act { get; set; }
        public string CID { get; set; }
        public byte DbAutSt { get; set; }
        public byte CrAutSt { get; set; }
        public string NoteNm { get; set; }
        public int Err { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte PropPrc { get; set; }
        public int PropNo { get; set; }
        public byte ExAut { get; set; }
        public string Txt2 { get; set; }
        public string BankG { get; set; }
        public int VoGr1 { get; set; }
        public int VoGr2 { get; set; }
        public decimal VatAm { get; set; }
        public decimal FixCurAm { get; set; }
        public decimal FixAm { get; set; }
        public int CshDueDt { get; set; }
        public decimal CshCurAm { get; set; }
        public decimal CshAm { get; set; }
        public int PrevVoNo { get; set; }
        public int TransSt { get; set; }
        public int EFT1 { get; set; }
        public int EFT2 { get; set; }
        public int EFT3 { get; set; }
        public int EFT4 { get; set; }
        public byte DbTrnCl { get; set; }
        public byte CrTrnCl { get; set; }
        public int TmpTr { get; set; }
        public decimal PrtCurAm { get; set; }
        public decimal PrtAm { get; set; }
        public byte ClPrc { get; set; }
        public decimal AmExVAT { get; set; }
        public int DelActNo { get; set; }
        public decimal CstAm { get; set; }
        public string PictNo { get; set; }
        public string WebPg { get; set; }
        public decimal Free1 { get; set; }
        public decimal Free2 { get; set; }
        public decimal Free3 { get; set; }
        public decimal Free4 { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int GiroChSm { get; set; }
        public int PmtMt { get; set; }
        public int Un { get; set; }
        public int PrBt { get; set; }
        public decimal PmVaCAm { get; set; }
        public decimal PmVaAm { get; set; }
        public int DbTxCdP { get; set; }
        public byte DbTrnClP { get; set; }
        public int CrTxCdP { get; set; }
        public byte CrTrnClP { get; set; }
        public int WfId { get; set; }
        public int PLDNo { get; set; }
        public int PLDFlow { get; set; }
        public string ExtRef1 { get; set; }
        public string ExtRef2 { get; set; }
        public int Dt1 { get; set; }
        public int Dt2 { get; set; }
        public int BankCon { get; set; }
        public int BankAcLn { get; set; }
        public decimal PmVaAmCD { get; set; }
        public decimal FreeAm { get; set; }
        public decimal FreeCurA { get; set; }
        public int PStYrPr { get; set; }
        public int PEnYrPr { get; set; }
        public decimal SmDb { get; set; }
        public decimal SmCr { get; set; }
        public decimal BankAm { get; set; }
        public string ExtRef3 { get; set; }
        public int Cur2 { get; set; }
        public decimal ExRt2 { get; set; }
        public decimal CurAm2 { get; set; }
        public int RealJNo { get; set; }
        public int EftFrmTp { get; set; }
        public int PrK { get; set; }
        public int StrtPer { get; set; }
        public int RealLnNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int Ctry { get; set; }
        public short EsTxTrm { get; set; }
    }
}
