//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vat
    {
        public int VatNo { get; set; }
        public decimal Rt { get; set; }
        public int IncAcNo { get; set; }
        public int CrEUAc { get; set; }
        public int DbWthAc { get; set; }
        public int CrWthAc { get; set; }
        public int CstAcNo { get; set; }
        public int OutwAcNo { get; set; }
        public int AfterDt { get; set; }
        public decimal NewRt { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte Gross { get; set; }
        public int WdrAcNo { get; set; }
        public int DbRevAc { get; set; }
        public int CrRevAc { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public int EsVatAc { get; set; }
    }
}
