//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VismaEntities : DbContext
    {
        public VismaEntities()
            : base("name=VismaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ac> Acs { get; set; }
        public virtual DbSet<AcBal> AcBals { get; set; }
        public virtual DbSet<AcGr> AcGrs { get; set; }
        public virtual DbSet<AcInt> AcInts { get; set; }
        public virtual DbSet<AcPr> AcPrs { get; set; }
        public virtual DbSet<ActInf> ActInfs { get; set; }
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorSocMe> ActorSocMes { get; set; }
        public virtual DbSet<ActPrc> ActPrcs { get; set; }
        public virtual DbSet<AcTr> AcTrs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Agr> Agrs { get; set; }
        public virtual DbSet<AgrAcc> AgrAccs { get; set; }
        public virtual DbSet<AgrStruct> AgrStructs { get; set; }
        public virtual DbSet<Altinn> Altinns { get; set; }
        public virtual DbSet<AltinnLog> AltinnLogs { get; set; }
        public virtual DbSet<AltProd> AltProds { get; set; }
        public virtual DbSet<AOProdInf> AOProdInfs { get; set; }
        public virtual DbSet<ARArch> ARArches { get; set; }
        public virtual DbSet<AssLink> AssLinks { get; set; }
        public virtual DbSet<Aut> Auts { get; set; }
        public virtual DbSet<AutInvOp> AutInvOps { get; set; }
        public virtual DbSet<BalGr> BalGrs { get; set; }
        public virtual DbSet<BankAc> BankAcs { get; set; }
        public virtual DbSet<BankCon> BankCons { get; set; }
        public virtual DbSet<Bgt> Bgts { get; set; }
        public virtual DbSet<BgtLn> BgtLns { get; set; }
        public virtual DbSet<BPart> BParts { get; set; }
        public virtual DbSet<BPmt> BPmts { get; set; }
        public virtual DbSet<BPmtLn> BPmtLns { get; set; }
        public virtual DbSet<ChLog> ChLogs { get; set; }
        public virtual DbSet<ChQue> ChQues { get; set; }
        public virtual DbSet<CmpRsp> CmpRsps { get; set; }
        public virtual DbSet<CombG> CombGs { get; set; }
        public virtual DbSet<CombMat> CombMats { get; set; }
        public virtual DbSet<CsDoc> CsDocs { get; set; }
        public virtual DbSet<CsDocF> CsDocFs { get; set; }
        public virtual DbSet<CsDocLn> CsDocLns { get; set; }
        public virtual DbSet<Ctry> Ctries { get; set; }
        public virtual DbSet<Cur> Curs { get; set; }
        public virtual DbSet<CurCData> CurCDatas { get; set; }
        public virtual DbSet<CurCor> CurCors { get; set; }
        public virtual DbSet<CustBal> CustBals { get; set; }
        public virtual DbSet<CustDocL> CustDocLs { get; set; }
        public virtual DbSet<CustTr> CustTrs { get; set; }
        public virtual DbSet<DecFVar> DecFVars { get; set; }
        public virtual DbSet<DeclCd> DeclCds { get; set; }
        public virtual DbSet<DelAd> DelAds { get; set; }
        public virtual DbSet<DelAlt> DelAlts { get; set; }
        public virtual DbSet<Delim> Delims { get; set; }
        public virtual DbSet<DelimG> DelimGs { get; set; }
        public virtual DbSet<DelTmBal> DelTmBals { get; set; }
        public virtual DbSet<Df> Dfs { get; set; }
        public virtual DbSet<DfLn> DfLns { get; set; }
        public virtual DbSet<Doc> Docs { get; set; }
        public virtual DbSet<DocLink> DocLinks { get; set; }
        public virtual DbSet<DstKey> DstKeys { get; set; }
        public virtual DbSet<DstLn> DstLns { get; set; }
        public virtual DbSet<EDIErr> EDIErrs { get; set; }
        public virtual DbSet<EdiFormId> EdiFormIds { get; set; }
        public virtual DbSet<EDIMsg> EDIMsgs { get; set; }
        public virtual DbSet<EDITrLog> EDITrLogs { get; set; }
        public virtual DbSet<EDocInfo> EDocInfoes { get; set; }
        public virtual DbSet<EDocLog> EDocLogs { get; set; }
        public virtual DbSet<EmlCfgFrm> EmlCfgFrms { get; set; }
        public virtual DbSet<EmpPath> EmpPaths { get; set; }
        public virtual DbSet<EmTpl> EmTpls { get; set; }
        public virtual DbSet<ErrLog> ErrLogs { get; set; }
        public virtual DbSet<EsTxStmtL> EsTxStmtLs { get; set; }
        public virtual DbSet<EsTxTrm> EsTxTrms { get; set; }
        public virtual DbSet<ExRt> ExRts { get; set; }
        public virtual DbSet<ExRt2> ExRt2 { get; set; }
        public virtual DbSet<ExtConf> ExtConfs { get; set; }
        public virtual DbSet<FactComp> FactComps { get; set; }
        public virtual DbSet<FormCh> FormChes { get; set; }
        public virtual DbSet<FreeInf1> FreeInf1 { get; set; }
        public virtual DbSet<FreeInf2> FreeInf2 { get; set; }
        public virtual DbSet<FreeInf3> FreeInf3 { get; set; }
        public virtual DbSet<FrmData> FrmDatas { get; set; }
        public virtual DbSet<Hol> Hols { get; set; }
        public virtual DbSet<Ind> Inds { get; set; }
        public virtual DbSet<InfNeed> InfNeeds { get; set; }
        public virtual DbSet<InfTp> InfTps { get; set; }
        public virtual DbSet<IntFVar> IntFVars { get; set; }
        public virtual DbSet<IntLn> IntLns { get; set; }
        public virtual DbSet<IntRt> IntRts { get; set; }
        public virtual DbSet<InvTx> InvTxes { get; set; }
        public virtual DbSet<ItemLoc> ItemLocs { get; set; }
        public virtual DbSet<JobDstCmd> JobDstCmds { get; set; }
        public virtual DbSet<Lang> Langs { get; set; }
        public virtual DbSet<Loc> Locs { get; set; }
        public virtual DbSet<MaCustTr> MaCustTrs { get; set; }
        public virtual DbSet<MaSupTr> MaSupTrs { get; set; }
        public virtual DbSet<MsgFrom> MsgFroms { get; set; }
        public virtual DbSet<MsgTo> MsgToes { get; set; }
        public virtual DbSet<Mst> Msts { get; set; }
        public virtual DbSet<MtInf> MtInfs { get; set; }
        public virtual DbSet<NoSr> NoSrs { get; set; }
        public virtual DbSet<NtfCd> NtfCds { get; set; }
        public virtual DbSet<OpCustTr> OpCustTrs { get; set; }
        public virtual DbSet<OpSupTr> OpSupTrs { get; set; }
        public virtual DbSet<Ord> Ords { get; set; }
        public virtual DbSet<OrdAtt> OrdAtts { get; set; }
        public virtual DbSet<OrdBa> OrdBas { get; set; }
        public virtual DbSet<OrdDBa> OrdDBas { get; set; }
        public virtual DbSet<OrdDoc> OrdDocs { get; set; }
        public virtual DbSet<OrdDocAtt> OrdDocAtts { get; set; }
        public virtual DbSet<OrdDocF> OrdDocFs { get; set; }
        public virtual DbSet<OrdDocLn> OrdDocLns { get; set; }
        public virtual DbSet<OrdJ> OrdJs { get; set; }
        public virtual DbSet<OrdLn> OrdLns { get; set; }
        public virtual DbSet<OrdLnBa> OrdLnBas { get; set; }
        public virtual DbSet<PicLst> PicLsts { get; set; }
        public virtual DbSet<PLCom> PLComs { get; set; }
        public virtual DbSet<PLDFData> PLDFDatas { get; set; }
        public virtual DbSet<PLDFDatU> PLDFDatUs { get; set; }
        public virtual DbSet<PLDFDoc> PLDFDocs { get; set; }
        public virtual DbSet<PLDFDocU> PLDFDocUs { get; set; }
        public virtual DbSet<PLDFGMem> PLDFGMems { get; set; }
        public virtual DbSet<PLDFGr> PLDFGrs { get; set; }
        public virtual DbSet<PLDFType> PLDFTypes { get; set; }
        public virtual DbSet<PLDocGen> PLDocGens { get; set; }
        public virtual DbSet<PmtAgr> PmtAgrs { get; set; }
        public virtual DbSet<PmtMt> PmtMts { get; set; }
        public virtual DbSet<PmtTrm> PmtTrms { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PrDcMat> PrDcMats { get; set; }
        public virtual DbSet<PrKey> PrKeys { get; set; }
        public virtual DbSet<PrLn> PrLns { get; set; }
        public virtual DbSet<Prod> Prods { get; set; }
        public virtual DbSet<ProdCat> ProdCats { get; set; }
        public virtual DbSet<ProdCust> ProdCusts { get; set; }
        public virtual DbSet<ProdDesc> ProdDescs { get; set; }
        public virtual DbSet<ProdProc> ProdProcs { get; set; }
        public virtual DbSet<ProdTr> ProdTrs { get; set; }
        public virtual DbSet<ProdTr2> ProdTr2 { get; set; }
        public virtual DbSet<Prog> Progs { get; set; }
        public virtual DbSet<Prop> Props { get; set; }
        public virtual DbSet<PropBal> PropBals { get; set; }
        public virtual DbSet<PropCl> PropCls { get; set; }
        public virtual DbSet<PropTr> PropTrs { get; set; }
        public virtual DbSet<Proxy> Proxies { get; set; }
        public virtual DbSet<PrRep> PrReps { get; set; }
        public virtual DbSet<Prtcp> Prtcps { get; set; }
        public virtual DbSet<Purc> PurcS { get; set; }
        public virtual DbSet<PurcSLn> PurcSLns { get; set; }
        public virtual DbSet<R1> R1 { get; set; }
        public virtual DbSet<R10> R10 { get; set; }
        public virtual DbSet<R10Bal> R10Bal { get; set; }
        public virtual DbSet<R11> R11 { get; set; }
        public virtual DbSet<R11Bal> R11Bal { get; set; }
        public virtual DbSet<R12> R12 { get; set; }
        public virtual DbSet<R12Bal> R12Bal { get; set; }
        public virtual DbSet<R1Bal> R1Bal { get; set; }
        public virtual DbSet<R2> R2 { get; set; }
        public virtual DbSet<R2Bal> R2Bal { get; set; }
        public virtual DbSet<R3> R3 { get; set; }
        public virtual DbSet<R3Bal> R3Bal { get; set; }
        public virtual DbSet<R4> R4 { get; set; }
        public virtual DbSet<R4Bal> R4Bal { get; set; }
        public virtual DbSet<R5> R5 { get; set; }
        public virtual DbSet<R5Bal> R5Bal { get; set; }
        public virtual DbSet<R6> R6 { get; set; }
        public virtual DbSet<R6Bal> R6Bal { get; set; }
        public virtual DbSet<R7> R7 { get; set; }
        public virtual DbSet<R7Bal> R7Bal { get; set; }
        public virtual DbSet<R8> R8 { get; set; }
        public virtual DbSet<R8Bal> R8Bal { get; set; }
        public virtual DbSet<R9> R9 { get; set; }
        public virtual DbSet<R9Bal> R9Bal { get; set; }
        public virtual DbSet<RealJ> RealJs { get; set; }
        public virtual DbSet<RealJLn> RealJLns { get; set; }
        public virtual DbSet<RemLtr> RemLtrs { get; set; }
        public virtual DbSet<RepNt> RepNts { get; set; }
        public virtual DbSet<Re> Res { get; set; }
        public virtual DbSet<ResRsv> ResRsvs { get; set; }
        public virtual DbSet<RptLbl> RptLbls { get; set; }
        public virtual DbSet<RspTp> RspTps { get; set; }
        public virtual DbSet<Rsv> Rsvs { get; set; }
        public virtual DbSet<RVo> RVoes { get; set; }
        public virtual DbSet<RVoLn> RVoLns { get; set; }
        public virtual DbSet<ScanCd> ScanCds { get; set; }
        public virtual DbSet<SEMtInf> SEMtInfs { get; set; }
        public virtual DbSet<Ser> Sers { get; set; }
        public virtual DbSet<SESnapInf> SESnapInfs { get; set; }
        public virtual DbSet<ShpBal> ShpBals { get; set; }
        public virtual DbSet<Src> Srcs { get; set; }
        public virtual DbSet<StatPr> StatPrs { get; set; }
        public virtual DbSet<Stc> Stcs { get; set; }
        public virtual DbSet<StcBal> StcBals { get; set; }
        public virtual DbSet<StrFVar> StrFVars { get; set; }
        public virtual DbSet<Struct> Structs { get; set; }
        public virtual DbSet<SupBal> SupBals { get; set; }
        public virtual DbSet<SupTr> SupTrs { get; set; }
        public virtual DbSet<TaskJ> TaskJs { get; set; }
        public virtual DbSet<TaxAcGr> TaxAcGrs { get; set; }
        public virtual DbSet<TaxAcInf> TaxAcInfs { get; set; }
        public virtual DbSet<Templ> Templs { get; set; }
        public virtual DbSet<TemplAcc> TemplAccs { get; set; }
        public virtual DbSet<TemplTp> TemplTps { get; set; }
        public virtual DbSet<TenancyF> TenancyFs { get; set; }
        public virtual DbSet<TSBal> TSBals { get; set; }
        public virtual DbSet<TSCal> TSCals { get; set; }
        public virtual DbSet<TSGr> TSGrs { get; set; }
        public virtual DbSet<TspAgr> TspAgrs { get; set; }
        public virtual DbSet<TspZ> TspZs { get; set; }
        public virtual DbSet<TxCd> TxCds { get; set; }
        public virtual DbSet<TxCdAut> TxCdAuts { get; set; }
        public virtual DbSet<TxStmtL> TxStmtLs { get; set; }
        public virtual DbSet<Txt> Txts { get; set; }
        public virtual DbSet<TxtCd> TxtCds { get; set; }
        public virtual DbSet<TxTrm> TxTrms { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Upd> Upds { get; set; }
        public virtual DbSet<UpdBnd> UpdBnds { get; set; }
        public virtual DbSet<UpdMa> UpdMas { get; set; }
        public virtual DbSet<UpdVo> UpdVoes { get; set; }
        public virtual DbSet<UsrComb> UsrCombs { get; set; }
        public virtual DbSet<UsrDelim> UsrDelims { get; set; }
        public virtual DbSet<Vat> Vats { get; set; }
        public virtual DbSet<VoSr> VoSrs { get; set; }
        public virtual DbSet<VoTp> VoTps { get; set; }
        public virtual DbSet<WaBnd> WaBnds { get; set; }
        public virtual DbSet<WaMa> WaMas { get; set; }
        public virtual DbSet<WaVo> WaVoes { get; set; }
    }
}
