//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoTp
    {
        public int VoTpNo { get; set; }
        public string StdTxt { get; set; }
        public byte InpTxt { get; set; }
        public byte InpCur { get; set; }
        public byte AffTrn { get; set; }
        public byte IgnTxCd { get; set; }
        public int DbAc { get; set; }
        public int CrAc { get; set; }
        public byte SugAm { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public int Pri { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public byte PropPrc { get; set; }
        public byte UpdOrd { get; set; }
        public byte Per { get; set; }
        public int SrNo { get; set; }
        public byte CompExRt { get; set; }
        public byte ExAut { get; set; }
        public byte RepInf { get; set; }
        public byte TrnCl { get; set; }
        public int VoTpPrc { get; set; }
        public byte ClPrc { get; set; }
        public int PgElNo { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public decimal PmVCshP { get; set; }
        public decimal PmVOtP { get; set; }
        public string Txt2Def { get; set; }
        public string ProdNo { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
    }
}
