//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exf.InvAppr.Sync.Visma.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaBnd
    {
        public int BndNo { get; set; }
        public string Descr { get; set; }
        public int ValDt { get; set; }
        public short AcYr { get; set; }
        public short AcPr { get; set; }
        public short TxYr { get; set; }
        public short TxTrm { get; set; }
        public int SrNo { get; set; }
        public int R1 { get; set; }
        public int R2 { get; set; }
        public int R3 { get; set; }
        public int R4 { get; set; }
        public int R5 { get; set; }
        public int R6 { get; set; }
        public decimal SmDb { get; set; }
        public decimal SmCr { get; set; }
        public decimal CtrlSm { get; set; }
        public byte SrcTp { get; set; }
        public int SrcJNo { get; set; }
        public byte Keep { get; set; }
        public byte Att { get; set; }
        public byte Susp { get; set; }
        public int Dupl { get; set; }
        public int ChDt { get; set; }
        public short ChTm { get; set; }
        public string ChUsr { get; set; }
        public byte LckSt { get; set; }
        public int ChPrc { get; set; }
        public int ChSm { get; set; }
        public int BankAcNo { get; set; }
        public decimal BankIB { get; set; }
        public decimal BankOB { get; set; }
        public decimal CpBankCh { get; set; }
        public int BtPro { get; set; }
        public int RevDt { get; set; }
        public short RevAcYr { get; set; }
        public short RevAcPr { get; set; }
        public short RevTxYr { get; set; }
        public short RevTxTrm { get; set; }
        public string R7 { get; set; }
        public string R8 { get; set; }
        public string R9 { get; set; }
        public string R10 { get; set; }
        public string R11 { get; set; }
        public string R12 { get; set; }
        public int PrBt { get; set; }
        public int Cur { get; set; }
        public decimal CSmDb { get; set; }
        public decimal CSmCr { get; set; }
        public int AcNo { get; set; }
        public int CustNo { get; set; }
        public int Seller { get; set; }
        public int Cur2 { get; set; }
        public int PrvJNo { get; set; }
        public int PrvBndNo { get; set; }
        public decimal CSmDb2 { get; set; }
        public decimal CSmCr2 { get; set; }
        public decimal SmDbExVat { get; set; }
        public decimal SmCrExVat { get; set; }
        public int CreDt { get; set; }
        public short CreTm { get; set; }
        public string CreUsr { get; set; }
        public short EsTxTrm { get; set; }
        public short RevEsTxTrm { get; set; }
    }
}
